### ISSUE TITLE
Some systems getting stuck for hours in pip install

### ISSUE THREAD

**Issue by kaylairish** [jmschrei/pomegranate#1012]
Hi there! My project uses pomegranate, and some of my users are reporting that installing pomegranate is taking a few hours. This has happened on a few different machines of different ages (Mac and PC)  and it seems to get stuck on 
"Collecting Pomegranate- Using cached pomegranate-0.14.8.tar.gz (4.3 MB) -Installing build dependencies ..." 

Do you recommend I try the command "pip install --no-cache-dir pomegranate"? The systems taking hours to install aren't getting errors, it seems.

I attempted on my own computer just now, and it took a tad (30s-1m) longer to install pomegranate than my other packages, but it went through. Do you have any ideas for why this might be happening?

**Comment by jmschrei** [comment]
Potentially it is because it has to build the Cython code locally. I tried providing wheels for Linux and Windows, but potentially these aren't compatible with your system. Regardless, I'm in the middle of a complete rewrite of pomegranate to use PyTorch as the backend (https://github.com/jmschrei/torchegranate), which should resolve many of the installation issues that people encounter.

**Comment by kaylairish** [comment]
Thank you for the information on this. Do you know when torchegranate might be released in a stable form?

**Comment by jmschrei** [comment]
Today! So, I'm closing this issue.
