### ISSUE TITLE
[Suggestion] Expose `Distribution` class via public API

### ISSUE THREAD

**Issue by AKuederle** [jmschrei/pomegranate#1015]
I think it would make sense to expose the base `Distribution` class via the "public" API.

This would help with typing of user code and probably this is required when implementing custom distributions.

**Comment by jmschrei** [comment]
I'm not sure what this means. Everything is public in Python.

**Comment by jmschrei** [comment]
I think that's the right signal to send, though. You shouldn't ever be creating a `Distribution` object directly in your code, and you should only use the `Distribution` when implementing your own distributions. I still view that as private because I don't see a semantic difference between distributions that I've implemented and custom distributions that the user implements, in terms of public/private. Basically, if private meant that a user should never touch them in any circumstance, you're saying that the user is unable to make custom extensions that use such methods. I know in some other languages private literally means that the function/method cannot be accessed outside the code, but Python isn't like those.

Please re-open if you'd like to keep chatting -- always happy to hear alternate perspectives.
