### ISSUE TITLE
Linear Gaussian Bayesian Networks

### ISSUE THREAD

**Issue by jmschrei** [jmschrei/pomegranate#106]
This has been a big issue for a while in that I don't support continuous output conditional probabilities or their Bayesian network counterparts.

**Comment by tbsexton** [comment]
Any updates here? As I mentioned in #232, the ability to read/write BN's with pmml would be wonderful, but their [primary documentation](http://dmg.org/pmml/v4-3/BayesianNetwork.html) even demonstrates a use-case for linear gaussian node probabilities. 

Not sure how I might be able to help, since I'm more used to using PyMC3 (e.g. and somewhat hacky [implementation of that example here](https://gist.github.com/tbsexton/1349864212b25cce91dbe5e336d794b4)) but I will take a look.

**Comment by jmschrei** [comment]
Unfortunately not. I fell through the discrete Bayesian network structure learning rabbit hole and haven't actually had time to learn what an efficient way to implement this would be. Do you have a good reference for inference in LGBN or hybrid networks?

**Comment by tbsexton** [comment]
It's not particularly my area of expertise, I'm afraid. I did find a decent walk-through from [this class](https://www.ics.uci.edu/~dechter/courses/ics-275b/spring-05/), specifically [these slides on continuous/hybrid BN inference](https://www.ics.uci.edu/~dechter/courses/ics-275b/spring-05/handouts/Inference%20in%20Continuous%20and%20Hybrid%20Networks.ppt). 

Still, the described method (much like the R package BNlearn, as noted [here](http://www.bnlearn.com/examples/fit/)) only seems to allow discrete variables to have discrete parents (ensuring it's linear Gaussian), which now that I'm looking the PMML example doesn't restrict to. 

I think the most typical way to do inference on a general hybrid BN will be some form of sampling or a variational method.

**Comment by andy6975** [comment]
Hi! Is this issue open for contribution? I would like to work on it. Thanks!

**Comment by jmschrei** [comment]
It is unlikely this will be implemented unless someone would like to contribute it.
