### ISSUE TITLE
Sample function of Bayesian network

### ISSUE THREAD

**Issue by yfpeng1234** [jmschrei/pomegranate#1106]
Dear author,
I found there might be a bug in Bayesian network's sample function.
![image](https://github.com/jmschrei/pomegranate/assets/135833420/94ce886f-01cd-4820-a2d2-3d3dcfbd997b)
For the above structure, assuming that the distribution list is ['c', 'a', 'b']:
so firstly we will sample for node 'c', but we don't have value of 'a' and 'b',
then we will sample for 'a' and 'b'.
Finally we will not get the value of 'c'
am I right?

**Comment by jmschrei** [comment]
Hm, looks like you might be right. This algorithm works if the nodes/features are already topologically sorted but, if they're not, I might need to add a second pass over the loop.

**Comment by jmschrei** [comment]
Sorry, no, I think the function is already correct.

The internal loop iterates over all nodes and their parents. If the node has been sampled from already, it ignores it. If the node is a parent node, it samples. If the node is conditional AND all the parents have been sampled from, it samples. At the end of this internal loop, the only distributions that will not be sampled from are conditional distributions where at least one parent was not sampled from yet. Thus, the outer loop repeats this internal procedure `self.d` times, ensuring that each node is seen. I'm going to change it to `self.d+1` times because I think there is an edge case based on ordering, but I think that if the function is running for you right now it should be correct.

In your example, we'd start off by trying to sample from C, being unsuccessful, and then moving on to A, where we could sample, and B, where we also could sample. Then, in the second iteration, we could sample from C, and wouldn't need to do A or B again. In the third iteration, we don't need to sample from anyone. 

Please re-open if you have concerns or think there's a mistake somewhere.
