### ISSUE TITLE
TypeError when training HMM with mixture state of multinomial Gaussians

### ISSUE THREAD

**Issue by mKaloer** [jmschrei/pomegranate#111]
When I attempt to train a HMM with a mixture model of multivariate gaussians, I get a `TypeError` stating that it cannot convert a `numpy.float64` to a `numpy.ndarray`. I'm unable to create any valid input; even inputting a sample of the same model will cause this error. This may be related to issue #6. I'm using the Pomegranate version currently on the master branch (395ff33).

This is the output:
```
----------
Custom Seq
----------
test.py:36: RuntimeWarning: invalid value encountered in double_scalars
  model.fit(sequences)
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._baum_welch_update'
Traceback (most recent call last):
  File "pomegranate/distributions.pyx", line 2018, in pomegranate.distributions.MixtureDistribution.from_summaries (pomegranate/distributions.c:33230)
TypeError: Cannot convert numpy.float64 to numpy.ndarray
Training improvement: nan
Total Training Improvement: nan
----------
Sample Seq
----------
test.py:40: RuntimeWarning: invalid value encountered in double_scalars
  model.fit([sample_seq])
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._baum_welch_update'
Traceback (most recent call last):
  File "pomegranate/distributions.pyx", line 2018, in pomegranate.distributions.MixtureDistribution.from_summaries (pomegranate/distributions.c:33230)
TypeError: Cannot convert numpy.float64 to numpy.ndarray
Training improvement: 0.287682072451781
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._baum_welch_update'
Traceback (most recent call last):
  File "pomegranate/distributions.pyx", line 2018, in pomegranate.distributions.MixtureDistribution.from_summaries (pomegranate/distributions.c:33230)
TypeError: Cannot convert numpy.float64 to numpy.ndarray
Training improvement: 0.0
Total Training Improvement: 0.287682072451781
```
This is a sample code that causes the error. It fits the model on some random data as well as on a sample from the model itself.
```
from pomegranate import *
import numpy as np

def create_hmm():
    # Create model with 3 states
    # Left-to-right: each state is connected to itself and its direct successor
    model = HiddenMarkovModel()
    mixtures = []
    for _ in range(0, 4): # 4 mixtures
        # Some random init values and identity cov matrix
        randSample = np.random.rand(104)
        mixtures.append(MultivariateGaussianDistribution(randSample, np.identity(104)))
    midState = State(MixtureDistribution(mixtures), name="mid")
    # Start and end without emissions
    startState = State(None, name="start")
    endState = State(None, name="end")
    model.add_states(startState, midState, endState)
    model.add_transition(model.start, startState, 1.0)
    model.add_transition(startState, midState, 0.2)
    model.add_transition(startState, endState, 0.6)
    model.add_transition(midState, midState, 0.5)
    model.add_transition(midState, endState, 0.5)
    model.add_transition(endState, model.end, 0.5)
    model.bake()
    return model

sequences = []
for i in range(0, 10):
    # Add an observation
    sequences.append([np.random.rand(104)])
model = create_hmm()
sample_seq = model.sample()
print("----------")
print("Custom Seq")
print("----------")
model.fit(sequences)
print("----------")
print("Sample Seq")
print("----------")
model.fit([sample_seq])
```

**Comment by jmschrei** [comment]
Hello! Sorry you're having trouble with pomegranate.

This issue ended up having several layers to it, most of it my fault.

* MixtureDistribution has been replaced by GeneralMixtureModel which has the same initialization call but much more functionality and flexibility.

* GeneralMixtureModel / MixtureDistribution had a bug in the sampling code which I have fixed.

* Your model is a big confusing. It looks like you're trying to build a profile HMM like those used in bioinformatics ([this link might help](https://github.com/jmschrei/yahmm/blob/master/examples/Global%20Sequence%20Alignment.ipynb)) The model comes initialized with silent start and end states, but you have a second silent state. You're basically going silent -> silent -> GMM -> silent -> silent. I removed the extra two silent states (though bake should have automatically removed the initial start state as part of its graph preprocessing step) 

* Your initialization of values using rand severely limits getting good convergence (or non-singular matrices) since you're randomly generating data without structure

I modified your code a little to reflect these changes, see here:

```python
from pomegranate import *
from pomegranate import MultivariateGaussianDistribution as MGD
import numpy as np

n = 104

def create_hmm():
    # Create model with 3 states
    # Left-to-right: each state is connected to itself and its direct successor
    model = HiddenMarkovModel()
    mixtures = [ MGD(np.random.randn(n) + i, np.identity(n)) for i in range(4) ]
    midState = State(GeneralMixtureModel(mixtures), name="mid")

    model.add_state(midState)

    model.add_transition( model.start, midState, 1.0 )
    model.add_transition( midState, midState, 0.8 )
    model.add_transition( midState, model.end, 0.2 )

    model.bake()
    return model

sequences = [ numpy.random.randn(10, n) + i % 4 for i in range(200) ]

model = create_hmm()
print("----------")
print("Custom Seq")
print("----------")
model.fit(sequences)

print model.sample()
```

This yields the following output:

```
----------
Custom Seq
----------
Training improvement: 100701.206635
Training improvement: 586.344809914
Training improvement: 846.709899537
Training improvement: 868.872157223
Training improvement: 1240.9217332
Training improvement: 1247.49891073
Training improvement: -1314.90662478
Total Training Improvement: 104176.647521
```

plus a really long and high dimensional random sample.

For future reference, if you want to train, you pass in a list of numpy arrays (or lists). This array is 1d if your model is 1d, or 2d if it is multivariate and has the shape (sample_size, n_dim). For example, the input for a univariate model 4 training samples might look like this:

```python
samples = [[4, 5, 7, 2], [2, 8, 4], [2], [2, 6, 8, 3, 5, 2]]
```

If you have a multivariate model two training samples might look like this:

```python
samples = [[[4, 5, 6], [1, 7, 2], [2, 3, 5]],      [[1, 0, 0], [0, 9, 2]]]
```

You'll need to get the latest version of the code from github in order to get the sample method to work. Let me know if this solves the problem for you!

**Comment by mKaloer** [comment]
No problem, I'm quite impressed by this library. Thanks a lot for your help, it works now. You are right that I don't need the start and end states and that I should use a normal distributed random.

**Comment by jmschrei** [comment]
Thanks! Let me know if you encounter any other issues or have any other suggestions.
