### ISSUE TITLE
distributions for GMM-HMM ?

### ISSUE THREAD

**Issue by huiyuHarvey** [jmschrei/pomegranate#122]
Hi, 

I know in pomegranate, `Normal distribution` and `Multivariate Gaussian Distribution` are supported, but what should I do to train a left-right GMM-HMM model ? 
I saw the benchmark with `hmmlearn` that GMM emission is also supported.

Thx.

**Comment by jmschrei** [comment]
Howdy

My understanding is that left-right hmms are just a specific structure of hmms. Since you can make any graph structure in pomegranate it really depends on what your data input space looks like. Using GMMs as emissions is just like using any other distribution, you define the GMM and use it as a distribution in a state.

**Comment by huiyuHarvey** [comment]
Thanks for ur answer.

But in the distribution.pyx, mixture Gaussian is not supported, right?

**Comment by jmschrei** [comment]
You should use GeneralMixtureModel as defined in gmm.pyx.

**Comment by huiyuHarvey** [comment]
Thx！
