### ISSUE TITLE
Error: pomegranate.fsm.FiniteStateMachine' object has no attribute 'add_states from 

### ISSUE THREAD

**Issue by igauravsehrawat** [jmschrei/pomegranate#15]
Getting this error while trying demo code from README.md

![error_log](http://s4.postimg.org/ouv63g2ml/Screenshot_from_2015_05_30_12_12_54.png)

I am doing it wrong ?

Thanks

**Comment by jmschrei** [comment]
That's an error on my side. It should be model.add_nodes, not model.add_states. Changes and nodes are used interchangably in my code as nodes are the common notation in Bayes nets and Markov notes, whereas states are more common in FSMs and HMMs.

I need to more fully make the two interchangable.

**Comment by jmschrei** [comment]
As a side note, I am going to fundamentally redo FSMs soon, as the more common representation is for states to hold information, and then edges to hold the conditions by which transitions happen. This will clarify their usage significantly.

**Comment by jmschrei** [comment]
This should be fixed. Most models (except HMMs) now interchangably use nodes and states, and edges and transitions, including in the names of the methods (".add_node" and ".add_state" should be supported for most models, doing the same thing, as well as ".add_edge" and ".add_transition" for FSMs.).

I have also redone FSMs such that each edge has a key which allows passage, instead of awkwardly having a distribution which de facto requires all edges to a given state have the same key. See examples/fsm_example.py or the README on pomegranate for details as to how to use them.

I am closing this issue now, reopen if there are still problems and I will fix them.

**Comment by jmschrei** [comment]
By fixed, I don't mean this example will work, but rather FSMs have been changed to a format which make conceptual sense, and new examples/unit tests have been added which pass. Please use those for reference!

**Comment by igauravsehrawat** [comment]
Thank you for looking into the issues.

Cheers
