### ISSUE TITLE
More uniform codestyle

### ISSUE THREAD

**Issue by nlgranger** [jmschrei/pomegranate#156]
Hi,
I noticed a few opportunities for improvement in the codestyle of the project, here are a few:
- tab indentation -> 4 space indentation
- spaces inside parenthesis and before comme -> remove
- number of blank lines between functions or classes
- long lines -> break
- possibly others.

These are far from being a show breaker, but if it is okay, I am willing to work on these. However, it might create merge conflicts with pending work.

If you think this is useless, you can close.

**Comment by jmschrei** [comment]
I don't mind someone going through and looking for improvements in the code style, but I don't know if I care about some of these things. Do you think it's worth your time to pursue this? What would the benefits be? It would likely have to wait until after the end of the month, as I am developing several aspects of the codebase for the next few weeks and don't want to interfere with your work.

**Comment by pixelou** [comment]
Well, for the beauty of it is not enough of an argument ;-) ?  
The space thing is easy to fix and would comply with the default behaviour of most editors. The long lines is convenient for people with small screens or dual view as in diffs. The rest might be useful to enable linting and static checks. I will see if I can have access to pycharm's professial edition and run the linter on cython files.

Nevertheless, since this is indeed very low priority, you can close for now or tell me later when I can work on this.

**Comment by jmschrei** [comment]
Okay. I appreciate the offer, regardless! I'll comment here again when we should discuss this again.

**Comment by jmschrei** [comment]
Lets start discussing this now--I still have some features I need to add, but hopefully I'll be done by the time we come to a consensus.

1. What is the difference for you between tabs and spaces? My understanding is most editors now can arbitrarily change between them, and I personally prefer tabs.
2. I used to favor having a lot of spaces inside parenthesis, but I've decided I don't like it as much. Personally, it seems nicer to do something like `numpy.sum(X)`, but if you're doing a more complex things to add in spaces, such as `numpy.sum( numpy.abs(X) - numpy.mean(X) )`. The spaces, to me, help clarify the internal logic. Parameters to functions should not have spaces though, e.g. `def func( a, b )` should be changed to `def func(a, b)`.
3. I'm told it should be 2 lines between functions/classes. Is this right?
4. This should already be done. Lets take a look at cases where it is not done.

I'd like to hear your thoughts on this.

**Comment by pixelou** [comment]
Hi there!

- Stackoverflow has rather long discussions about why they are equivalent, but I personnaly see a few advantages for spaces:
 * consistent display (even outside the editors like in the web-browser, email-viewer, terminal or diff editors)
 * (arguably) simpler block-selection for regex search, vim visual selection
 * easy fine alignment:
```python
return (blablabla,
        bliblibli)
```

- Agreed, especially around operators and groups. I'd suggest to write it like so `numpy.sum(numpy.abs(X) - numpy.mean(X))` to keep lines short if that can avoid a line break though.

- That is what I read indeed
- Some bash/sed/awk magic should do the trick here, especially if spacing is done with spaces ;-)

**Comment by jmschrei** [comment]
1. Lets leave it as tabs for now, I'm not convinced that spaces are better enough to change my coding style (as the primary contributor to the package). I'm open to revisiting this in the future.
2. It seems like this is going to be a bit subjective, but I think we're on the same page.
3. OK
4. OK

I think the best way to move forward is to do one file at a time so that the diff can fit in github, and we can agree on everything before you tackle the bigger files. If you submit PRs for FactorGraph and BayesianNetwork I'll take a look at them.

**Comment by pixelou** [comment]
I commit on my fork, one file at a time, and we can continue to discuss here until a PR seems ready, right?

I have started with base: https://github.com/pixelou/pomegranate/commit/9bff3266a307ecbe132906b266d66006fec9bd0b

I also have a few side notes that may or may not be of interest for you:

Maybe get rid of base.parameter and let the subclasses do their own stuff. `copy` is the only one to use it (in base.pyx) and it is possible to use on serialization to do the deep copying.

Are `__repr__` and `__str__` actually needed? The doc for `__repr__` states that it should return a readable (=short) representation for debugging, the whole dump is probably too big. Maybe let the subclasses implement their own at will here?

`GraphModel.dense_transition_matrix` assumes the existence of `out_edge_count`, `out_transitions` and `out_transition_log_probabilities` fields which are not defined as far as I can see. Maybe enforce their existence?

**Comment by jmschrei** [comment]
I would suggest submitting a separate pull request for each file. It seems simpler for me.

parameters is important. It creates a consistent way of calling the underlying parameters of the distribution. Maybe we will move this to distribution instead of base, but I'm keeping it as parameters for now.

You're right though that the dependencies for these objects may be a bit fuzzy for now. Lets put that on hold for a bit, because I created the Model and GraphModel object a few weeks ago in order to get model stacking working as much as possible, so I haven't cleaned everything up yet. I'll make everything more consistent slowly as I gain time (likely when my internship is over in two weeks)
