### ISSUE TITLE
Questions about HMM

### ISSUE THREAD

**Issue by ngoix** [jmschrei/pomegranate#157]
I have a few questions about the hmm implementation:
1) What is the training improvement? Is it the log-likelihood difference between the initialization and the final model?
2) Is there a way to access the achieved log-likelihood?
3) Can we add a prior on the transition matrix?

Thanks :) !

**Comment by jmschrei** [comment]
1) Yes. It's log_likelihood_trained - log_likelihood_initial 
2) Do you mean get a list of the improvements each iteration? Currently there is not, but I'd like to add a 'history' object like keras has.
3) Yes. You can add a prior on each edge, using "pseudocount=x" when you define the edge. like so

```
model.add_transition(a, b, pseudocount=0.6)
```

**Comment by jmschrei** [comment]
3) If you want to add the same pseudocount to each edge, you can pass in `transition_pseudocount=x` as a parameter to the fit method, as well. If you want to use edge-specific pseudocounts, you need to toggle `use_pseudocount=True` in the fit method. I know this is confusing, and I'll look into getting rid of that parameter soon.

**Comment by ngoix** [comment]
Thank you!
My question 2) was just about getting the log likelihood of the final model.

**Comment by jmschrei** [comment]
It returns the total improvement. You could run the model on all of your data again to get the raw log likelihood given the dataset.

**Comment by ngoix** [comment]
Sorry I didn't get your point. How can I have log_likelihood_trained from a second running?
`hmm.log_probability(X)` computes this, right?

**Comment by jmschrei** [comment]
Yes. Currently you need to pass in points one at a time, so `sum(hmm.log_probability(x) for x in X)` if X is your list of sequences.

**Comment by B4marc** [comment]
Hi, 
I am having some trouble to understand what exactly is going on in HMM. 
My understanding of an HMM is based on this paper (link) which describes the HMM as „An HMM is a doubly stochastic process with an underlying stochastic process that is not observable (it is hidden), but can only be observed through another set of stochastic processes that produce the sequence of observed symbols.“. 

So, I have a transition matrix (T) and a observation matrix (B) which allows me to find the probability of being in one state and observe a special observation in that state. 
To be more precise, getting from one state to another (say x to y= T[x,y]) and observe in this state this specific observation B[y,z]. 

X= State A
Y= state B
B[y,z]= probability of observing observation z in state y 

1)Is this meant by the reading docs of Pomegranate: „A HMM can be thought of as a general mixture model plus a transition matrix, where each component in the general Mixture model corresponds to a node in the hidden Markov model, and the transition matrix informs the probability that adjacent symbols in the sequence transition from being generated from one component to another.“?

2)Thus continuing my understanding for one sequence of one observation – using viterbi-algorithm – the probability is: max(T[x,y]*B[z]), right?

3) If this is right, do I need a probability for each observation per (each single) state? If yes, is this solved by continues observations by on distribution per observation per state? 
I guess not, since the input of „from_sample“ has one distribution for each state.

I tried to work these questions out by myself since I thought they are basics which someone should be able to see in the code, but my knowledge about python is not good enough to understand the forward_backward function where these calculations should be done. 

So, I would be very thankful for your help!

Thanks :)

**Comment by jmschrei** [comment]
Howdy

I think that introductory materials on HMMs might end up being more helpful than me. In general, a HMM is a probabilistic model that attempts to assign hidden states to each observation in a sequence, in contrast to a more classic machine learning model that assigns a single label to a fixed feature set. This distinction it important, because the label for some observation t is influenced by the label given to some observation t+1. The two components of a HMM are the emission matrix, which connect the observed sequence to the hidden states, and the transition matrix, which indicate the probabilities of assigning some hidden state to an observation given the previous hidden state assignment. Solving all potential assignments of hidden states to observations is a very difficult problem, but dynamic programming solutions have been created that can efficiently calculate this exactly. The `viterbi` algorithm is the hard version of this algorithm in that it explicitly assigns exactly one hidden state to each observation, while the `forward_backward` or `maximum a posteriori` algorithm is the soft version which assigns probabilities of each hidden state being assigned to each observation.

Let me know if you have other specific questions.

**Comment by B4marc** [comment]
Hi jmschrei, 
first of all, thank you very much for your help and quick response! 
Is it true to say (simplified): The assigned hidden state to each observation at the viterbi algorithm, is the state with highest probability; arising from transistion probability multiplicated by emission probability?

**Comment by jmschrei** [comment]
Yes, but to be specific, the Viterbi algorithm outputs the *path* with the highest probability of all paths that the observations could take through the model.
