### ISSUE TITLE
dealing with large corpora in markov chains

### ISSUE THREAD

**Issue by koaning** [jmschrei/pomegranate#163]
I am building a large Markov chain, here's my code. 

```
from pomegranate import *
import itertools as it

poke_names = file("/Users/code/Development/grabbel/demo_data/ikea_furniture.txt").read().split('\n')

def flatten(listOfLists):
    "Flatten one level of nesting"
    return it.chain.from_iterable(listOfLists)

tokens = flatten([ [t for t in name.replace(' ', '').replace("'", '')] for name in poke_names])
uniq_tokens = list(set(tokens))

product2 = [list(i) + [1.0/len(uniq_tokens)**2] for i in it.product(uniq_tokens, repeat=2)]
product3 = [list(i) + [1.0/len(uniq_tokens)**3] for i in it.product(uniq_tokens, repeat=3)]

d1 = DiscreteDistribution({t:1.0/len(uniq_tokens) for t in uniq_tokens})
d2 = ConditionalProbabilityTable(product2, [d1])
d3 = ConditionalProbabilityTable(product3, [d1, d2])

mc = MarkovChain(3)
mc.fit(poke_names, inertia = 0.01)

for i in range(20): 
    print("".join(mc.sample(20)))
```

In this case it seems to work fine because my corpus is small and hence the `produc2` and `product3` lists are relatively small. I am wondering if a markov chain can have a ‘defauldict’-like functionality to prevent the need for precalculation when the corpus grows. Right now the corpus is small (only letters) but you can imagine that if I wanted to do this for words that I’d need to generate a large product of a list to build up the conditional table. Memory wise this seems rather inefficient but also the only way for the api to allow for a smoothing factor (inertia). 

It may break the API, but would it be possible to have an API more similar to;

```
mc = MarkovChain(rank = 3, smoothing = 0.0001).fit(generator_obj)
```

I am investigating the latter by writing some python code around the markov chain. Are there other people who may like to see this feature?

**Comment by jmschrei** [comment]
I see what you're saying. This seems more like a feature for Conditional/Joint probability tables than with markov chains themselves. In this case, what you'd like is for combinations which exist in the data to be represented appropriately, but combinations which do not exist in the data to not explicitly be stored? I think a better way of doing this would be to use pseudocounts as a prior (and just store what the prior would be). I'll take a look, but would welcome a PR if you have an idea as well.

**Comment by koaning** [comment]
The prior approach would work too I suppose. I want to think about it some more too, but was wondering what your thoughts were.

**Comment by jmschrei** [comment]
I think you're right that it may be difficult to store conditional tables with many parents and many emission possibilities, and that a sparse approach can likely solve this if many of those combinations are not actually possible. This might be just as simple as using `dict.get(key)` instead of `dict[key]` right now, since I'm using a dictionary for the underlying storage. However, I'm looking to change CPTs to be a single underlying vector instead of a dictionary so that I can do operations on the C level with the GIL released, and so relying on dictionary functionality may impede that. I'll have to think about it some more as well and look into some papers on higher order markov chains. If you can find a paper which you think is promising that may speed up me implementing something. 

Honestly I added markov chains as an afterthought because it would be easy to do so, but I'm glad you're finding them useful, and so will bump it up on the things I should think about.

**Comment by koaning** [comment]
So my usecase is for generative approaches. Simulating Red Hot Chilli Pepper lyrics, pokemon names, ikea furniture names and midi notes. This might be a nichy feature and I can imagine people who are doing DNA simulations to be more interested in the speed... it's fine to not have support for this specific problem but I'm wondering if there might be. 

I'll think about this over the week/weekend too.

**Comment by jmschrei** [comment]
That sounds pretty cool. Does that mean that you want the sampling method to be fast and efficient, but don't care so much about the other methods?

Can you describe roughly what the emission size and parent size you'd like to be, so I can understand better the scale of your problems?

**Comment by koaning** [comment]
So if i want to make a markov chain for the english language, I'll assume that i have a corpus of about 20,000 words (this would be sufficient for lyrics, not wikipedia pages). Usually I'd like to generate a sentence at a time and I think I would not generate a markov chain that looks back more than 5 steps.
