### ISSUE TITLE
Improve model fitting logging

### ISSUE THREAD

**Issue by jmschrei** [jmschrei/pomegranate#175]
After each iteration in GMM/HMM training it should report the time it took to train that iteration. Calls to 'fit' should also return a "history" object like in keras which shows the dataset log probability at each iteration, time, and other relevant statistics.

**Comment by mrshu** [comment]
@jmschrei if you do not mind I'd like to help you out with this, since I found `pomegranate` quite useful in my own work, and could actually benefit from the additions requested by this issue.

Since this is a pretty broad issue, I decided to tackle it in multiple passes. The first one being the first sentence of this issue:

> After each iteration in GMM/HMM training it should report the time it took to train that iteration.

I took it a small step further and also report the total time it took to train a given GMM/HMM model in #269.

My next steps here would be designing a history-like object, taking Keras as the main source of inspiration, per your description above. If you do not mind me asking, can you think of any other relevant statistics one would like to find in a "history" of training apart from time, improvement and log probability? 

Thanks!
