### ISSUE TITLE
Learning algorithms ? 

### ISSUE THREAD

**Issue by ronojoy** [jmschrei/pomegranate#18]
@jmschrei, excellent work with the API - its the most intuitive amongst the several pgm libraries I have used. Are there plans of implementing learning algorithms in pomegranate ?

**Comment by jmschrei** [comment]
By learning algorithms I am assuming that you mean training of models on data. Most objects in pomegranate currently support training, such as all distributions except tables, HMMs, and GMMs. However, Factor Graphs and Bayes Nets currently do not support training. This is something I would like to add in the future, however I want to make sure I do it right. A unique challenge in training Bayes Nets / Factor Graphs is that all other model require no missing values in the training data, whereas Bayes Nets are great in part because they can train on incomplete data. 

As for when this will occur, I am uncertain. I am wrapping up an academic quarter right now, and will be leaving for a summer internship working on sklearn in a few weeks. It is one of the first things I intend to tackle when I devote my time to pomegranate again, though.

So briefly, there is a plan to implement them, but I am unsure when it will happen. If you need training immediately, it may be best to use another one of the excellent pgm packages which exist.

**Comment by ronojoy** [comment]
Yes, I was asking about training models on data, specifically for Bayes Nets and for Factor Graphs. (I noticed that training distributions is already implemented). It would be great to have both parameter learning and structure learning algorithms implemented. Ideally, a pandas data frame would be supplied as input data, possibly with missing values, and the output would be a  trained Bayes Net, with both probability distributions and structure learnt and missing data imputed.  I can do all of these things with other pgm libraries at the moment but I much prefer the Pythonic API in pomegranate so I will look forward the time when these features are implemented.

**Comment by jmschrei** [comment]
I agree. I think these fall under three distinct problems though;

(1) Training tables from data; relatively easy
(2) Imputing missing data given a Bayesian network; moderate
(3) Learning structure from data; more difficult
(4) Learning structure from incomplete data; involves EM-type algorithm where you switch between imputing data given a model and learning structure on that data; most difficult, but trivial once other components are implemented

None of these are ~super~ difficult, but time consuming to debug. Does your application require (4) to be completed, or if I implemented (1) would that be good enough for now?

**Comment by ronojoy** [comment]
Having (1) and (2) would be very good.  I do not have an immediate need for (3) and (4) but if they do get ready in the months ahead I would certainly use pomegranate for a  [workshop on reasoning under uncertainty](https://in.pycon.org/cfp/pycon-india-2015/proposals/reasoning-under-uncertainty-with-python/) later this year.

**Comment by jmschrei** [comment]
Okay. I can make that deadline. This is higher priority for me now that I know there is a strong use case.

**Comment by ronojoy** [comment]
Thanks - look forward to these in the weeks ahead! 

I came across [Lea](https://code.google.com/p/lea/)  recently - you might find it interesting.

**Comment by jmschrei** [comment]
I just added cython optimized updates for ConditionalProbabilityTable and JointProbabilityTable. I'll move on to updating BayesNets next.

**Comment by ronojoy** [comment]
Thanks. I'll take a look at the code and add an use case example.

**Comment by jmschrei** [comment]
Training for Bayesian networks has been added. The current signature is `model.train( items, weights=None, inertia=0.0, pseudocount=0.0 )`, where items is a list of lists, where each inner list is a data point. I am unsure how efficient it is, as it needs to reorder the data matrix for each node. The data matrix cannot be a numpy array, because it must support heterogeneous data types. 

I will consider the possibility of passing in transposed arrays (such that each row is all values of a variable, and each column is an item, allowing rows to be individual numpy arrays), but that's currently not supported. I also do not want to make pandas a requirement, despite how useful it may be in this situation. I will soon add in functionality to ~accept~ but not ~require~ a pandas dataframe, though.

**Comment by jmschrei** [comment]
@ronojoy, just checking in. Are you still planning on using pomegranate for your upcoming workshop? If so, what features of Bayesian learning need to be added to make it viable for you?

**Comment by ronojoy** [comment]
@jmschrei, sorry for the late reply. I still haven't thought of an alternative to pomegranate, so the answer is yes. It would be nice if we could have 

(2) Imputing missing data given a Bayesian network; moderate
(3) Learning structure from data; more difficult

implemented. I will not have time to talk about structure learning with missing data, so that is not needed for sure. Between (2) and (3), my priority is (3). I can then leave out missing data entirely from the workshop and focus only on parameter and structure learning. Also, I am not too particular about the distinction between exact and approximate inference/learning - any robust algorithm that is not unduly hard to explain will work fine. Thanks.

**Comment by jmschrei** [comment]
Okay. I will take a stab at implemented the Chow-Liu tree-building algorithm for the building of tree-like Bayesian networks. 

Can you give me a deadline? That will help me order my priorities for the next month.

**Comment by ronojoy** [comment]
The workshop runs between 2 - 3 October. I'll need a while to learn the internals of your implementation, so if you have something ready by the third week of September, that would be fine.

**Comment by jmschrei** [comment]
Imputation of missing data will be added in #29. It was not actually that difficult, since the difficult part was implementing the forward-backward inference, not extending it to matrices instead of rows. I should have Chow-Liu structure inference done as well. Let me know in that PR if you have any comments about the implementation.

**Comment by jmschrei** [comment]
Also, apologies about the delay. I have been focusing on rewriting parts of the distribution and HMM code to allow for multithreaded (not multi-process) training.

**Comment by ronojoy** [comment]
@jmschrei, thanks for letting me know. I'll have a look at it in a day or two and get back with comments.

**Comment by jmschrei** [comment]
I just wrapped up a major feature push for my PyData talk a week ago. I am planning on delving deeper into Bayesian network features in the coming weeks, and hopefully adding linear gaussian bayesian networks. I know I've put them off for a long time! Did you ever end up having comments?

**Comment by jmschrei** [comment]
I just added a lot to Bayesian networks, including a lot of the leg work for Bayesian network structure learning. I've added in the chow-liu tree building algorithm, which creates a tree Bayesian network as an approximation of the larger network. It can do this extremely efficiently. Let me me know if you give it a look.

**Comment by jmschrei** [comment]
Learning algorithms have been added.
