### ISSUE TITLE
simplify internal API / Allow users to easily roll their own models

### ISSUE THREAD

**Issue by nlgranger** [jmschrei/pomegranate#203]
Hi,
While reading through the code, I have found that some trickery is needed to handle a few things, and it make the code and the API more complicated than lazy-me would wish. On the top of my head:

- variable length sequences
- mono vs multi dimensional data
- multiple vs one sample at a time
- large datasets
- partial support of the sklearn interface

Some simplifications would make it easier to add new models and let users extend the library with their own models. As a side effect, it could help upgrade the documentation (https://github.com/jmschrei/pomegranate/projects/5).

Maybe this is just me being picky, but if you are indeed interested, I can give it a try and PR some propositions when ready.

**Comment by jmschrei** [comment]
Howdy

I'm not exactly sure what you're referencing, but I'd love to hear your suggestions. What things are you finding complicated as a user and what solutions would you like implemented? There certainly are some hacks in the backend but they're usually done to make the interface simpler to the user.

**Comment by pixelou** [comment]
All well considered, I might be exagerating the problem a bit, but I hope it can make a useful contribution.

Here is what I have been thinking about:

##### Add a setstate and getstate method (also provide default arguments for all constructors)
I think this is necessary to be compatible with scikit-learn's cross-validation.
Besides, it might make it easier to provide default implementations for serialization functions (`to_json`, `__reduce__`)

##### Constrain input shape
Scikit-learn reserves the first dimension for items stacking. So a one element sample of dimension 3 must have shape (1, 3), not (3,). If all function provide a method to treat batches intead of items, this allows you to use vectorized processing internally. For variable length inputs, functions may expect lists of those matrices as it is the case already.

##### Lock-free variable length data
Variable length inputs use lists and hence require to use the GIL. If you stack items together and pass an offset table to locate each one, I think it is possible to do all the work lock free.

##### provide mmap container for large arrays
For large datasets (this is probably common with variable length inputs), it might be possible to use numpy's mmaped arrays so that it is not necessary to split work into batches anymore.

**Comment by jmschrei** [comment]
I'm all for the first one. The second one I'm not sure I understand. Do you mean for log probability calculations? I'm already moving in that direction and support that as well.

For the third, I'm not sure what you mean that they use the GIL. HMMs have multithreaded training and are the most efficient model to train in parallel currently. Even mixtures of HMMs still work well. Can you elaborate?

mmap can be used for the parallelized `fit` function. I have an example somewhere where I train a large mixture model on 20gb, Maybe I need to write a more in depth tutorial on that and post it up.

**Comment by pixelou** [comment]
3- The lists of variable length arrays would be stacked together while regular arrays are kept as usual

```python
	def _data2array(self, X, weights=None, dtype=np.float64):
		# Concatenate samples into a single array for fast access

		if self.is_vl:
			durations = np.array([len(x) for x in X], dtype=np.int32)
			offsets = np.cumsum(durations)

			data = np.empty((np.sum(durations), self.d), dtype=dtype)
			o = 0
			for i, (x, d) in enumerate(zip(X, durations)):
				data[o:o + d, :] = x.reshape((-1, self.d))
				o = o + d

			return X, len(X), offsets

		else:
			if not isinstance(X, np.ndarray) or X.dtype != dtype:
				X =np.array(X, dtype=dtype)
			X = X.reshape((-1, self.d))
			return X, len(X), np.zeros((0,), dtype=np.int32)
```

Once the data is inside a single array, the GIL can be released right away, and one can use cython's parallelization over the samples if this is desirable. 
I am not sure how joblib works internally, but python's multiprocessing relies on serialization to pass data to/from the threads which incurs a small (acceptable?) overhead.

2 - I have not been very clear on this one: forcing a common representation of data lowers the number of methods one has to write to implement a model, it would be only:
```cython
	cdef void _log_probability(self, double[:, :] symbols,
	                               int n, int[:] offsets,
	                               double[:] log_probabilities) nogil
```
If the model supports/requires vl inputs, offsets is used, otherwise left blank.

(to be verified) Add a cython method for summarize so that is it not necessary to reaquire the GIL to call summarize on children distributions:
```cython
    cdef void _summarize(self, double[:, :] X, double[:] weights,
                                        int n, int[:] offsets) nogil:
```

4 - I can work on a container which simplifies the use of mmap for vl inputs if you are interested. That could come handy.

**Comment by jmschrei** [comment]
3 - I don't understand your issue. There is not a significant overhead during things the way they currently are. HMMs using variable length sequences achieve the closest to linear speedups with the number of cores of any of the models I currently use since so much time is spent in the forward/backward aspects of the algorithm. This seems needlessly complicated.

2 - There is a common representation of the data. I'm not following you. For example, if you have a mixture of HMMs you just call operations on the mixture and it automatically passes the data into the appropriate HMMs without requiring the user.

4 - Sure, I'd love to see more contributions from you.

**Comment by pixelou** [comment]
3 - Ok.
2 - I meant for people who contribute or add new models. There is currently: `Model._log_probability`, `Model._mv_log_probability`, `Model._vl_log_probability` and `Model._v_log_probability`. They are often higly redundant, and most of the time, only one is meaningful between variable length or not. So there is a potential for factorization. For example in gmm.pyx:

```cython
	if not self.is_vl_:
		X_ndarray = numpy.array(X)
		X_ptr = <double*> X_ndarray.data

	with nogil:
		for i in range(n):
			if self.is_vl_:
				with gil:
					X_ndarray = numpy.array(X[i])
					X_ptr = <double*> X_ndarray.data
				logp[i] = self._vl_log_probability(X_ptr, n)
			elif d == 1:
				logp[i] = self._log_probability(X_ptr[i])
			else:
				logp[i] = self._mv_log_probability(X_ptr+i*d)

	return logp_ndarray

cdef double _log_probability(self, double X) nogil:
	cdef int i
	cdef double log_probability_sum = NEGINF
	cdef double log_probability

	for i in range(self.n):
		log_probability = \
			(<Model> self.distributions_ptr[i])._log_probability(X) \
			+ self.weights_ptr[i]
		log_probability_sum = \
			pair_lse(log_probability_sum, log_probability)

	return log_probability_sum

cdef double _mv_log_probability(self, double* X) nogil:
	cdef int i
	cdef double log_probability_sum = NEGINF
	cdef double log_probability

	for i in range(self.n):
		log_probability = \
			(<Model> self.distributions_ptr[i])._mv_log_probability(X) \
			+ self.weights_ptr[i]
		log_probability_sum = \
			pair_lse(log_probability_sum, log_probability)

	return log_probability_sum

cdef double _vl_log_probability(self, double* X, int n) nogil:
	cdef int i
	cdef double log_probability_sum = NEGINF
	cdef double log_probability

	for i in range(self.n):
		log_probability = \
			(<Model> self.distributions_ptr[i])._vl_log_probability(X, n) \
			+ self.weights_ptr[i]
		log_probability_sum = \
			pair_lse(log_probability_sum, log_probability)

	return log_probability_sum
```
I can make a demo of a factored version for a few models to show you what I am mean if you are interested. But we can keep thing as is since it's working well right now.

For 1) I'd like to modify the behaviour of from_json: it would parse the class field as an importable path so that Models from 3rd parties are loadable:

```python
@classmethod
def from_json(cls, s):
    """Deserialize a model from its JSON representation.

    Parameters
    ----------
    s : str
        A JSON model state as returned by :ref:`to_json`

    Returns
    -------
    model : object
        A properly instanciated distribution.

    Note
    ----
    The deserialized JSON data should be a dictionary containing at least
    a 'class' key with a string item of the form:
    _importable_module_._ClassName_.

    This helps the default implementation of :func:`Model.from_json`
    forward the JSON representation to the appropriate class for any type
    of model.

    Example
    -------
    >>> import pomegranate
    >>>
    >>> s = { 'class': 'pomegranate.UniformDistribution',
    >>>  	  'start': 0.0,
    >>> 	  'stop': 1.0 }
    >>> d = pomegranate.Model.from_json(s)
    >>>
    >>> print(isinstance(d, pomegranate.UniformDistribution))
    True
    >>> print(d.start)
    0.0
    >>> print(d.stop)
    1.0
    """

    d = json.loads(s)
    if 'class' not in d.keys():
        raise ValueError("missing 'class' field")

    if cls.__name__ == "Module":  # Explicitely called implementation
        path = d.split('.')

        distmodule = importlib.import_module('.'.join(path[:-1]))
        distclass = getattr(distmodule, path[-1])
        return distclass.from_json(s)

    else:  # Default inherited implementation
        obj = cls()
        cls.set_params(d['state'])
        return obj
```

**Comment by jmschrei** [comment]
3 - If you can show that your method is faster, I'd of course love to incorporate it. I just don't think it will be the case. 

2 - I agree. What I was saying is that this redundancy is because I haven't moved the API over to make the log_probability API call vectorized, but I wanted the benefits of doing vectorized operations in the backend for BLAS. I'd be happy to look at a prototype you have, but this is a known issue which I'll be fixing at some point in the future when I get time again. 

1 - Is the point that someone else should be able to write a distribution and have it be used by pomegranate, and save/load properly? I'd agree, but right now the bigger issue is that the person would have to be proficient enough in Cython to copy the _log_probability and _summarize APIs properly which is unlikely. At some point I want to give models python tags so that they use the optimized cython version if available or the slower python version if not available.

**Comment by pixelou** [comment]
2-3 - I'm travelling at the moment but I'll work on it when I come back.
1 - That's what I meant.

**Comment by pixelou** [comment]
Sorry to bump this up, but do you have any opinion on the above (negative opinions accepted :-) )

**Comment by jmschrei** [comment]
No, the bump was great. I had forgotten about this in the flurry of recent work I've needed to do. I will respond soon, but thanks for the thought you've put into this.

**Comment by jmschrei** [comment]
It looks like I didn't respond soon, but since I added in support for custom Python models and distributions this issue should be resolved. Thanks again for your thoughts on the subject--- it certainly helped push me to add in Python-only customization.
