### ISSUE TITLE
Setting random seed to 0 in pomegranate/pomegranate/hmm.pyx bake? 

### ISSUE THREAD

**Issue by epierson9** [jmschrei/pomegranate#235]
Is there a motivation for doing this in lines 858 - 859? It is producing unintended side effects in my code.

**Comment by jmschrei** [comment]
Off the top of my mind I think the reasoning is that it enforces that the topological ordering of the states is consistent across multiple runs. Since the columns of all predictions and such are based on this ordering, it seemed beneficial to allow users to connect a column to a given state no matter how many times they ran the script. If you'd like to add in randomness later on in the script I think you can add in something like `numpy.random.seed(time.time())`.

**Comment by epierson9** [comment]
I understand, thanks!

The problem with this is that it subtly sets global state in a way that can mess up functions which call pomegranate + use randomness, and these bugs are very hard to track down. For example, I was trying to run ten trials where I randomly generated data for each trial and then fit a pomegranate HMM to the data. My results for trial 1 were different from trial 2, but trials 2 - 10 were identical, as a consequence of the seed being set to 0. Eventually I tracked this problem to hmm.pyx, but it took a while, and some users might not notice the problem at all. I think it would be safer to not reset random state, or to allow users to set the random state themselves, or to explicitly flag in the documentation that this is done.

**Comment by jmschrei** [comment]
It's certainly a fair criticism. Do you know of any instances where other libraries have handled it? I'm not sure I want to hard code in randomizing the seed at the end of `bake` because it'd be inconsistent with how numpy does it internally. Perhaps there's a `numpy.seed.reset` type deal somewhere?

**Comment by jmschrei** [comment]
I'm going to close this for now. Re-open if there are any other issues.

**Comment by alexanderschliep** [comment]
Some students of mine stumbled over this and I fully agree with OP that this can easily cause problems, which would be hard to detect. I'd consider resetting the random seed a bug — at a bare minimum this should be very clearly documented, which it isn't in the latest incarnation of the documentation.

**Comment by robinkrahl** [comment]
I think the proper way to deal with his would be using a new instance of [`numpy.random.RandomState'](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState) for the calculations you want to perform with a fixed seed.
