### ISSUE TITLE
Exception ValueError: '"[\'A-4\', \'C5\', \'E-5\']" is not in list' in 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize' ignored

### ISSUE THREAD

**Issue by awanger** [jmschrei/pomegranate#237]
Apologies if this is a stupid question. I am trying to train an HMM with labeled data. This is my code:

`chord_labels = [   ["['A-4', 'C5', 'E-5']"], ["['A-4', 'C5', 'E-5']"],...,  ["['A-4', 'C5', 'E-5']"]   ]`

`chord_labels` is a numpy array of lists that each contain a single string representation of a chord. So, in this example `"['A-4', 'C5', 'E-5']"` is an A-minor chord. When I run

`hmm.fit(sequences=X, labels= chord_labels, weights=None, algorithm='labeled')`

I get

`Exception ValueError: '"[\'A-4\', \'C5\', \'E-5\']" is not in list' in 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize' ignored`

I'm not sure what this means. Does this mean my labels are not formatted correctly?

**Comment by jmschrei** [comment]
Howdy

Is one of your states named "['A-4', 'C5', 'E-5']", or do you have three states named "A-4", "C5", and "E-5"? In any case, I -think- that you have to give the index of the state and not the name, so you'd have to do `labels = map(hmm.states.index, chord_labels)`. I'd like for it to take in state name soon because that's more intuitive, but I don't think that's how it works right now.

**Comment by awanger** [comment]
One of the states is named "['A-4', 'C5', 'E-5']". I tried running your suggestion

`labels = map(hmm.states.index, chord_labels)`

and got `ValueError: ["['A-4', 'C5', 'E-5']"] is not in list`. I checked `hmm.states` and the state is definitely in the list. It seems like when I try to get the index of a state, it doesn't recognize the name of it.

I also tried giving the state object itself so that

`chord_labels =  #list of lists each containing one state object`

but I get

`Total Training Improvement: 0.0`

**Comment by awanger** [comment]
Also, I was just wondering exactly what algorithm is run when we specify "labeled". Thanks!

**Comment by nuno-s** [comment]
I awanger, i'm having the same problem as you... The same errors, and the same result with a list of list each containing one state object...

**Comment by nuno-s** [comment]
I had a mistake in code... My list of list was empty. Know works with a list of list each containing one state object...

The final result was:

Training improvement: 590495.1561579907
Training improvement: 1.7462298274040222e-10
Total Training Improvement: 590495.1561579909

But the results are poor. I need to investigate more.

**Comment by awanger** [comment]
@nuno-s I doubled and tripled check that my list of lists and it looks like what I need it to look like. Could you post some of your code so I can compare mine and yours? Thanks!

**Comment by nuno-s** [comment]
I had the same problem as you, so i open a issue, probably at the same time as you. So you can see my code and my o problem in this link:

https://github.com/jmschrei/pomegranate/issues/238

After read this thread, and see what you do, i made this changes:

Create a function, array parameter is a bi-dimensional array with the labels, and  s0, s1, s2 ,s3, s4 are the states.

for each position of array (remember that is a 2 dimensional array) i verify what is the label, and for each label, i append to list the correct state.

`def estados (array,s0,s1,s2,s3,s4):

    listoflists = []
    a_list = []
    for i in range(len(array)):
        a_list.clear()
        for x in range(len(array[i])):
            if (array[i][x] == 0):
                a_list.append(s0)
            if (array[i][x] == 1):
                a_list.append(s1)
            if (array[i][x] == 2):
                a_list.append(s2)
            if (array[i][x] == 3):
                a_list.append(s3)
            if (array[i][x] == 4):
                a_list.append(s4)
        listoflists.append(a_list)
    return listoflists

`
So i call the function

`labels = estados(array_labels,s0,s1,s2,s3,s4)`

And do the fit

`model.fit(array_treino, labels=labels, algorithm='labeled',n_jobs=2)`


If you have any doubts, please ask!!!

**Comment by jmschrei** [comment]
@awanger the algorithm that is run is just basic count collection. You count the number of times you have label y1 before label y2 and use those counts to determine the transition probabilities, and then you group observations by label and use that to update the emission probabilities in a single MLE.

**Comment by awanger** [comment]
@nuno-s I'm having a bit trouble following along. Could you print `array_treino`, `labels`, and `array_labels`?

And `array_treino` is the sequence, I presume?

**Comment by nuno-s** [comment]
@awanger

Ok, i will put and explain my code.

I have one pandas data frame with 5 columns, where z_anomaly is the label collum

`df_aux = pd.DataFrame({
                        'ac_x': ac_x.tolist(),'ac_y': ac_y.tolist(),'ac_z': ac_z.tolist(),'a_speed': speed.tolist(),
                        'z_anomaly': anomaly_array.tolist()})`

After that, i split the data frame in to list of list(each list position has a list with a sequence, in this case a sequence of 120 rows), where "array_treino" has the data, and array_labels the labels. This labels are numbers: 0,1,2,3,4.

```
array_treino = np.array_split((df_aux.ix[:,0:4].values),120)
array_labels = np.array_split((df_aux.ix[:,4].values),120)
```


this is a example of the labels list:
![image](https://cloud.githubusercontent.com/assets/26788135/24586306/0189d438-1795-11e7-8b40-a40b5225d7ba.png)


But, using this array labels, i had the same error as you.

> Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 3 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list

So, after read this issue, i create a function to compare the value of each position of array_labels, and create a new list of list with the corresponded state:

**The 4 states creation**
```
s0 = State(MultivariateGaussianDistribution(means_0,co_0),name="0")
s1 = State(MultivariateGaussianDistribution(means_1,co_1),name="1")
s2 = State(MultivariateGaussianDistribution(means_2,co_2),name="2")
s3 = State(MultivariateGaussianDistribution(means_3,co_3),name="3")
s4 = State(MultivariateGaussianDistribution(means_4,co_4),name="4")
```

**The invocation of estados() function**
`labels = estados(array_labels,s0,s1,s2,s3,s4)` 

**The estados() function**

```
def estados (array,s0,s1,s2,s3,s4):

    listoflists = []
    a_list = []
    for i in range(len(array)):
        a_list.clear()
        for x in range(len(array[i])):
            if (array[i][x] == 0):
                a_list.append(s0)
            if (array[i][x] == 1):
                a_list.append(s1)
            if (array[i][x] == 2):
                a_list.append(s2)
            if (array[i][x] == 3):
                a_list.append(s3)
            if (array[i][x] == 4):
                a_list.append(s4)
        listoflists.append(a_list)
    return listoflists
```

After this, the variable labels has pomegranate states objects:

> [{
    "class" : "State",
    "weight" : 1.0,
    "distribution" : {
        "class" : "Distribution",
        "parameters" : [
            [
                7.34966802764379,
                -0.05160554359639239,
                0.015204592115187753,
                0.14137258753373572
            ],
            [
                [
                    3.4958503784667356,
                    0.03797507077503893,
                    -0.007148163641170462,
                    0.05246373525207985
                ],
                [
                    0.03797507077503893,
                    0.6087079908871743,
                    0.04780639047870456,
                    0.09207378111664698
                ],
                [
                    -0.007148163641170462,
                    0.04780639047870456,
                    0.35972301998859035,
                    0.02599012437967522
                ],
                [
                    0.05246373525207985,
                    0.09207378111664698,
                    0.02599012437967522,
                    1.18057164142198
                ]
            ]
        ],
        "frozen" : false,
        "name" : "MultivariateGaussianDistribution"
    },
    "name" : "0"
}, {
    "class" : "State",
    "weight" : 1.0,
    "distribution" : {
        "class" : "Distribution",
        "parameters" : [
            [
                7.34966802764379,
                -0.05160554359639239,
                0.015204592115187753,
                0.14137258753373572
            ],
            [
                [
                    3.4958503784667356,
                    0.03797507077503893,
                    -0.007148163641170462,
                    0.05246373525207985
                ],
                [
                    0.03797507077503893,
                    0.6087079908871743,
                    0.04780639047870456,
                    0.09207378111664698
                ],
                [
                    -0.007148163641170462,
                    0.04780639047870456,
                    0.35972301998859035,
                    0.02599012437967522
                ],
                [
                    0.05246373525207985,
                    0.09207378111664698,
                    0.02599012437967522,
                    1.18057164142198
                ]
            ]
        ],
        "frozen" : false,
        "name" : "MultivariateGaussianDistribution"
    },
    "name" : "0"
}, {
    "class" : "State",
    "weight" : 1.0,
    "distribution" : {
        "class" : "Distribution",
        "parameters" : [
            [
                7.34966802764379,
                -0.05160554359639239,
                0.015204592115187753,
                0.14137258753373572
            ],
            [
                [
                    3.4958503784667356,
                    0.03797507077503893,
                    -0.007148163641170462,
                    0.05246373525207985
                ],
                [
                    0.03797507077503893,
                    0.6087079908871743,
                    0.04780639047870456,
                    0.09207378111664698
                ],
                [
                    -0.007148163641170462,
                    0.04780639047870456,
                    0.35972301998859035,
                    0.02599012437967522
                ],
                [
                    0.05246373525207985,
                    0.09207378111664698,
                    0.02599012437967522,
                    1.18057164142198
                ]
            ]
        ],
        "frozen" : false,
        "name" : "MultivariateGaussianDistribution"
    },
    "name" : "0"
}, {
    "class" : "State",
    "weight" : 1.0,
    "distribution" : {
        "class" : "Distribution",
        "parameters" : [
            [
                7.34966802764379,
                -0.05160554359639239,
                0.015204592115187753,
                0.14137258753373572
            ],
            [
                [
                    3.4958503784667356,
                    0.03797507077503893,
                    -0.007148163641170462,
                    0.05246373525207985
                ],
                [
                    0.03797507077503893,
                    0.6087079908871743,
                    0.04780639047870456,
                    0.09207378111664698
                ],
                [
                    -0.007148163641170462,
                    0.04780639047870456,
                    0.35972301998859035,
                    0.02599012437967522
                ],
                [
                    0.05246373525207985,
                    0.09207378111664698,
                    0.02599012437967522,
                    1.18057164142198
                ]
            ]
        ],
        "frozen" : false,
        "name" : "MultivariateGaussianDistribution"
    },
    "name" : "0"
}, {
    "class" : "State",
    "weight" : 1.0,
    "distribution" : {
        "class" : "Distribution",
        "parameters" : [
            [
                7.34966802764379,
                -0.05160554359639239,
                0.015204592115187753,
                0.14137258753373572
            ],
            [
                [
                    3.4958503784667356,
                    0.03797507077503893,
                    -0.007148163641170462,
                    0.05246373525207985
                ],
                [
                    0.03797507077503893,
                    0.6087079908871743,
                    0.04780639047870456,
                    0.09207378111664698
                ],
                [
                    -0.007148163641170462,
                    0.04780639047870456,
                    0.35972301998859035,
                    0.02599012437967522
                ],
                [
                    0.05246373525207985,
                    0.09207378111664698,
                    0.02599012437967522,
                    1.18057164142198
                ]
            ]
        ],
        "frozen" : false,
        "name" : "MultivariateGaussianDistribution"
    },
    "name" : "0"
}, 


 
For last, and as you say very well, array_treino it's the sequence for training the algorithm, and each position, has 120 rows, with 3 columns. (treino is the Portuguese word for training)

![image](https://cloud.githubusercontent.com/assets/26788135/24586353/9595ad9a-1796-11e7-93e9-05b982de12c8.png)

So i call the fit method like this:

`model.fit(array_treino, labels=labels, algorithm='labeled',n_jobs=2)`

Where **array_treino** is an array of data sequences and **labels** it's an array of pomegranate states sequences

With this i don't have any error, at the end i obtain this results:

> Training improvement: 646830.4689839948
Training improvement: -5.820766091346741e-11
Total Training Improvement: 646830.4689839948

I think that are bad results, because when i do the predict his fail completely. So, i probably still doing something wrong with my data, or distributions... I really don't know, it's my first time using HMM. I hope that you can get better results.

**Comment by sniderbr** [comment]
@awanger, @jmschrei:  I've experienced the same (`ValueError: <some state name> is not in list`) when trying to perform supervised HMM training.  Similar to @nuno-s, I found that converting each label sequence from a list of _labels_ (state names) to a seqence of _actual states_ works, for example:

```python
# given some multi-observation training_data and corresponding training_labels
state_names = [state.name for state in hmm.states]
state_indices = [[state_names.index(s) for s in seq] for seq in training_labels]
state_values = [[hmm.states[i] for i in seq] for seq in state_indices]
hmm.fit(training_data, labels=state_values, algorithm='labeled')
```

This works but seems counterintuitive; I expect others would assume that `labels=` could use `training_labels` directly, rather than the conversion to `state_values`.

**Comment by awanger** [comment]
@sniderbr After you trained the model, did you get good results when you tried decoding later? Just wondering. I think I'm going try once more tomorrow.

**Comment by sniderbr** [comment]
@awanger Yes, the model does pretty well after training, although it's not quite as good as training with Baum-Welch without knowledge of the labels, depending on the data (in my case, `labeled` was great for subject-dependent data, but `baum-welch` was better for subject-independent data).  I did discover (the hard way) that the HMM state sequence is different, in that the states in the HMM are not in the same order as they were specified when I instantiated the HMM (they end up in sorted order, alphabetically).  Once I figured out that the state sequence was according to the new ordering, it all made sense.  For example, following my code above:

```python
path = hmm.predict(test_data, algorithm='viterbi')
predicted = [hmm.states[i].name for i in path]
```

...rather than trying to use the sequence `path` as indices into my original list of state names.

**Comment by jmschrei** [comment]
The states aren't necessarily sorted alphabetically, they are just sorted topologically and silent states are forced to the back. This makes the internals simpler, but unfortunately it does change the ordering.

**Comment by sniderbr** [comment]
Aha, thank you for the clarification @jmschrei — good to know.

**Comment by himat** [comment]
@sniderbr I've been trying to do labelled fitting as well, but I don't understand why you have a list of lists for your labels.

`state_indices = [[state_names.index(s) for s in seq] for seq in training_labels]`
Wouldn't your labels normally just be a single list?

**Comment by jmschrei** [comment]
@himat both your data and labels should be a list of lists, because presumably you are training on more than one sequence. If there is only one sequence, you still pass in a list of a single list, i.e. `[[0, 1, 2, 0, 2, 1...]]` or whatever your data looks like.

**Comment by jmschrei** [comment]
I'm going to close this issue for now. Please re-open or open a new issue if you encounter similar problems in the future.
