### ISSUE TITLE
How does an HMM learn automatically

### ISSUE THREAD

**Issue by himat** [jmschrei/pomegranate#259]
This is a conceptual question.

I'm trying to wrap my head around how it's even possible for an HMM to learn the distribution of states based on unlabeled data. How could it possibly know which feature values correspond to which state if the data isn't labeled? 

Does it only work because you provide some initial estimates of what _you_ think the probabilities are?
Such as when you do `State(NormalDistribution(1.0, .2), name="rainy"` or specify a transition probability?

If this is the case, then if your initial hand-made estimates are off, then the whole HMM would do poorly in learning right?

**Comment by jmschrei** [comment]
You should read about expectation-maximization, specificially the Baum-Welch algorithm, for a more precise answer. Basically, you're exactly right that it only works because you start with an initialization. The algorithm follows roughly as below:

(0) Initialize your distributions, either manually through expert knowledge or through something like k-means
(1) Calculate the probability of every sample under each distribution (Expectation)
(2) Use these probabilities as weights, and do weighted MLE to update the parameters of each distribution (Maximization)

repeat steps 1 and 2 until convergence. The reasoning is that if you have NormalDistribution(0, 1), you wouldn't expect it to faithfully model 7.8, but instead of trying to set an arbitrary cutoff point for what you use to update the distribution, you say that 7.8 will contribute a very tiny amount to the update of the distribution. Hopefully, points that have a small weight under one distribution have a larger weight under another distribution.

**Comment by jmschrei** [comment]
I'm going to go ahead and close this. Please re-open if you have any other questions.
