### ISSUE TITLE
Sparse Conditional Probability Tables for Bayesian Networks

### ISSUE THREAD

**Issue by UndeadKernel** [jmschrei/pomegranate#261]
Hi Jacob. In another issue, you mentioned that you'd like to receive suggestions for new things to implement in pomegranate. Hence, I am creating this issue.

When dealing with large bayesian networks, conditional probability tables will contain many zeroes. Instead of keeping track of these zeroes, a BN could record only non-zero entries. This would reduce the memory required by a model for, both, saving it on disk and directly working with it.

**Comment by jmschrei** [comment]
Thanks for the suggestion, it's a good idea that I've had on my mind for a bit. Unfortunately it is a little bit tricky. It certainly can drastically reduce memory load and in theory reducing computational time (especially in the Markov chain case where you're looking back several time steps, not just one). It would have to come with a corresponding Sparse Joint Probability Table. 

However, most of the computation in pomegranate is done at the C level with the GIL released. The easiest implementation of a sparse matrix is using a dictionary, which would require the GIL and have to be done on the python level. This may make some computational tasks (such as fitting model parameters) take longer. OTOH it may be worth it to provide the option for people who are having difficulty fitting large models in memory and don't care as much about computation time.

I will keep it in mind and let you know if I make progress in the area. For the next month or so I'm going to be wrapping up my research work before summer so it may take a little bit to get implemented though.

**Comment by jmschrei** [comment]
It is unlikely I'll be able to add this in, but one could add in their own custom distribution now that does this.

**Comment by mlindsk** [comment]
Hi,

First of all; what an interesting package with many features! Regarding the zero entries in the CPTs, you might be interested in this new paper about this very detail:

[https://arxiv.org/abs/2103.03647](url)

It provides a new (sparse) representation of (probability) tables and defines multiplication/division, marginalization etc. It is implemented in the `R` programming language:

[https://github.com/mlindsk/sparta](url)

However, all the back-end code is written in `c++` (see the src/ folder) and hence, the code can be used in other software packages with a little adaption. Feel free, at any point to use the code. 

Note: There are cases where it is actually worse to use a sparse representation because of the overhead - you might be interested in Figure 2 to see this.

sparta is also used as the back-end for table operations in the new `jti` (junction tree inference) package which can handle extremely complex networks with giant CPTs due to sparta

`https://github.com/mlindsk/jti`

If you decide, that this post is not well suited here, feel free to delete it. This was just my two cents ;)

/Mads

**Comment by jmschrei** [comment]
Thanks for the pointer! I'll take a look soon.
