### ISSUE TITLE
Need recommendations for a simple project

### ISSUE THREAD

**Issue by renderit** [jmschrei/pomegranate#275]
Hi there! Great work here! I'm working on a simple project using probabilistic and bayesian analysis.. I have "**groups**" and each group contains "**buttons**". Every group contains different "buttons". I'm trying to analyze and **predict** "given the group, which function you will use next **with time**" .. on a time series scale - as time progresses. Like if he used a button recently, chance he might not use it again.
For example: 
```
my_dict = 
{ "group-1" : ["b1", "b4", "b5"],
"group-2": ["b2", "b6"],
"group-3": ["b8", "b9", "b10"]
...
```
![untitled diagram](https://user-images.githubusercontent.com/8347939/27109776-c0b0e764-5059-11e7-9ec1-943021661b47.png)

**Comment by jmschrei** [comment]
Sorry for the delay. I'm not entirely clear on what it is you're trying to accomplish. Does each group have a unique set of buttons? Do you know these groups/button combinations in advance?

**Comment by renderit** [comment]
@jmschrei Thanks for getting back.. Yes, each group has unique set of buttons? 
And yes, I do know these group/button combination in advance.. Imagine if you're trying to learn a new device, which has these buttons on it. So
- if you used any button in the last 10 minutes(for example), you might not use it again since you know about it now, (but you might come back to it at some point in future)
- Trying to understand maybe 'usage' data and predicting next button you'll use
Hope this is a lil more clear. Happy to share more..

**Comment by jmschrei** [comment]
This sounds like you'd want to scrap the buttons and build a Markov chain on the grounds. Essentially you want to learn the transition probabilities from one group to another group. A problem with this is that the Markov property will make the model time invariant (using a group at time 1 will give you the same prediction as using the group at time 100). To counter this, you could also include "time" as a variable like a group in order to condition the probabilities on time. I can't recall if multivariate discrete Markov chains are supported in pomegranate right now, but if you think this is the right thing to do I can advise you on how to mimic this using a HMM.

**Comment by renderit** [comment]
@jmschrei Interesting! Yes, "time" is what confusing me.. and I couldn't find any applied solution in python. Also how come HMM? Are you thinking about updating the transition matrix at every step(after every button press?). How should I deal with time?

**Comment by jmschrei** [comment]
A Markov chain corresponds to a HMM where each node has only a single emission, and each emission has only a specific node. There is no reason why you would want to use a HMM to create a Markov chain unless the library that you're using has more features implemented for HMMs than for Markov chains ;)

Depending on the amount of data you have, you can deal with time where each click is it's own time "slice", or you can deal with it where you bin a certain number of clicks into the same time slice. Essentially, if you're modeling each click independently, you'd have each state in a time slice corresponding uniquely to a group and only have transitions to the nodes in the NEXT time slice. This allows you to learn transition parameters that are unique to each time slice. However, this assumes that ALL patterns are time specific, not that it will learn time-independent and time-dependent patterns together, unless these time-independent patterns are common enough that they can be learned at any given time slice. A pitfall for this problem is that you would need to manually create the model going out a certain number of time slices, and it could only go out that far. 

If you're looking for a simple model that is conditioned on time, I'm not sure what the best alternative model would be, though it may exist. Sorry I can't be of more help.
