### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by sali45** [jmschrei/pomegranate#312]
The input for labels needs to be more clear as to what it's looking for. Currently I have

         modelWave = HiddenMarkovModel('Gestures').from_samples(NormalDistribution, 3, training, labels=[sw0, sw1, sw2, sw3], algorithm='labeled')
    Y = modelWave.predict(test, algorithm='viterbi')

where `sw0, sw1, ...` are states. I get the error shown in the title. What exactly is the label argument supposed to hold?

**Comment by jmschrei** [comment]
It should work with just a list of lists. Can you provide a minimally reproducing example? Also, you should remove the ('Gestures') fragment, so that it just reads 

```python
modelWave = HiddenMarkovModel.from_samples(NormalDistribution, 3, training, labels=[sw0, sw1, sw2, sw3], algorithm='labeled', name='Gestures')
```

**Comment by sali45** [comment]
What do the list of lists contain? Say I have one big list [...] with smaller lists inside like [[][][][]]. What would go in the smaller lists?

I also, I would be happy to provide a minimally reproducing example, but I'm not sure what that would be. 

Thanks for the help. I really appreciate it.

**Comment by jmschrei** [comment]
If you have the latest version of the code, you should be able to do the following:

```
X = [[12, 16, 2, 5], [7, 8, 3, 5, 8], [2, 5, 7]]
labels = [['model-start', 's1', 's2', 's3', 's3', 'model-end'], ['model-start', 's1', 's1', 's2', 's2', 'model-end'], ['model.start', 's2', 's2', 's3', 'model-end']]

modelWave = HiddenMarkovModel.from_samples(NormalDistribution, 3, X, labels=labels, algorithm='labeled', state_names=['s1', 's2', 's3'], ends=True, name='model')
```

Labels is a list of lists, where each inner list is the state object or name of the state in the path that the sample travels down. This means it always begins with the start state '{HMM-Name}-start' or `model.start` if `model` is an actual HMM object. Optionally it can end with '{HMM-Name}-end' or `model.end` if you want to have an explicit end state. If you have entirely symbol emitting states (like using the `from_samples` method, then each label past the start state corresponds to the label for that position in the actual data. Meaning that in my first set of labels, (`['model-start', 's1', 's2', 's3', 's3', 'model-end']`), 's1' corresponds to 12, 's2' corresponds to 16, 's3' corresponds to both 2 and 5. You need to define these state names using the `state_names` argument for `from_samples`, otherwise it won't know how to tag them (something that could be improved, I suppose).

A minimally reproducing example is the smallest script you can write that reproduces the error. It helps me debug because instead of guessing what the problem is, I can actually run it and poke it until I figure out what the problem is. The 'minimally' part is important because I don't want to have to deal with hundreds of lines of unnecessary code. 

Also make sure that you've pulled the most recent version of the code from GitHub, not just using pip. I recently improved this aspect of HMM learning.

**Comment by sali45** [comment]
This is the code I preprocess my data with. I have csv files representing accelerometer data in data frames for x, y, and z axes. I also use a `sliding-window` and a `sample-difference` preprocessing step before I run PCA. 
    def windows(files):
          df = pd.DataFrame(columns=['timestamp', 'time skipped', 'x', 'y', 'z', 'label']).set_index('timestamp')
          for my_files in files:
              with open(os.path.join("/Users", "saqibali", "PycharmProjects", "sensorLogProject", "Data", my_files),
                  'rU') as my_file:
                 for d in sliding_window(sample_difference(my_file), 50, 25):
                     df = df.append(d)
         return df[['x', 'y', 'z']]


    def principal_components():
        pca = PCA(n_components=3)
        training_result = pca.fit_transform(windows(training_files))
        testing_result = pca.transform(windows(test_files))
        return training_result, testing_result

Here is my hmm file. I have 3 gestures in my training set, so I created 3 different models for each one. For the states, I used Gaussian distributions but that choice was just a pure guess. Furthermore, I randomly chose mean and variance because I have no idea how to correctly pick them out, but that's another story and maybe we can sort that out in another issue. 

    def hidden_markov_model(training, test):
        # modelCircle
        # 4 states
        sc0 = State(NormalDistribution(2, 4), name='0')
        sc1 = State(NormalDistribution(3, 5), name='1')
        sc2 = State(NormalDistribution(2, 5), name='2')
        sc3 = State(NormalDistribution(1, 6), name='3')

        # modelWave
        # 4 states
        sw0 = State(NormalDistribution(5, 6), name='0')
        sw1 = State(NormalDistribution(2, 6), name='1')
        sw2 = State(NormalDistribution(1, 3), name='2')
        sw3 = State(NormalDistribution(0, 1), name='3')

        # modelPickUp
        # 2 states
        sp0 = State(NormalDistribution(1, 4), name='0')
        sp1 = State(NormalDistribution(2, 5), name='1')


        modelCircle = HiddenMarkovModel.from_samples(NormalDistribution, 3, training, labels=[sc0, sc1, sc2, sc3], algorithm='labeled', name='CircleGesture')
        X = modelCircle.predict(test, algorithm='viterbi')

        modelWave = HiddenMarkovModel.from_samples(NormalDistribution, 3, training, labels=[sw0, sw1, sw2, sw3], algorithm='labeled', name='WaveGesture')
        Y = modelWave.predict(test, algorithm='viterbi')

        modelPickUp = HiddenMarkovModel.from_samples(NormalDistribution, 3, training, labels=[sp0, sp1], algorithm='labeled', name='PickUpGesture')
        Z = modelPickUp.predict(test, algorithm='viterbi')

**Comment by jmschrei** [comment]
I'm not sure I understand what you're doing. Why are you creating state objects if you're just going to learn the model directly from data? You're also using `labels` incorrectly. Like I showed in my example, `labels` needs to have the same shape as your variable `training`, because you're assigning one label to each observation + start and end states. It looks like you're confusing `labels` and `state_names`. `labels` is not the unique set of labels. 

I'm also not sure where your labels are. Do you have per-observation labels? If you don't, and want to do unsupervised training of the model (the more typical task for HMMs) then all you need to do is `model = HiddenMarkovModel.from_samples(NormalDistribution, 4, training)`. If your data is three dimensional (because you have an x, y, z axis) then you'll want to do `model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 4, training)` instead, as normal distribution is for 1d data.

**Comment by sali45** [comment]
Ok, that makes a lot more sense thanks! The thing is though, I want to use the HMM for classification. Would I still be able to use this model to classify the 3 different gestures? As in, for each of the three models I create, I will pass in the training data that contains all the data from all three gestures. Then I will test each gesture separately from each model to see if the model predicts the correct gesture. Does that make sense? I'm just wondering if an unsupervised HMM is appropriate for my task.

**Comment by jmschrei** [comment]
It is possible to create a single HMM that branches off into three independent models after the start state, and use the forward-backward algorithm to identify which of the three sub-models is most likely given the observation. However, this ends up being very complicated very quickly, and pomegranate is flexible enough to provide a simpler interface. Generally, if you'd like to analyze sequences, you'd want to use a hidden Markov model. If you're trying to determine which underlying model fits the data best, you'd want to use Bayes' rule, just like you do for a naive Bayes classifier (for labeled data) or a mixture model (for unlabeled data).

If you have labeled ~sequences~ (as opposed to each observation in the sequence being labeled) then you can use a BayesClassifier, like the following.

```
X = ~your sequences in a numpy array~
y = ~the label for each sequence, set(0, 1, 2)

modelCircle = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 4, X[y==0])
modelWave = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 4, X[y==1])
modelPickUp = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 4, X[y==2])

model = BayesClassifier([modelCircle, modelWave, modelPickUp])
model.predict(new_sequences)
```

If your sequences are all unlabeled, the initialization gets more complicated. Do you have labeled sequences to train on?

**Comment by sali45** [comment]
So, going back to my PCA implementation above, you can see that I iterate through a list of files. 

    training_files = [
        'Circle1Accelerometer.csv',
        'Circle2Accelerometer.csv',
        'PickUpPhoneAccelerometer1.csv',
        'PickUpPhoneAccelerometer2.csv',
        'Wave1Accelerometer.csv',
        'Wave2Accelerometer.csv',
    ]

    test_files = [
        'Circle3Accelerometer.csv',
        'PickUpPhoneAccelerometer3.csv',
        'Wave3Accelerometer.csv'
    ]

They contain time-series accelerometer data like this:

     1501514704.745, 0, -0.055908, -0.729034, -0.645294, 3
     1501514704.755, 0, -0.046158, -0.709091, -0.650177, 3
     1501514704.765, 0, -0.036469, -0.699554, -0.672668, 3
     1501514704.775, 0, -0.027908, -0.695740, -0.678070, 3

where the third, fourth, and fifth columns are `x`, `y`, and `z` respectively. The last column is the label. In this case, `Circle` is `3`. I didn't include that column in my PCA file, but now I'm thinking I should have. I represent these `csv` files as `Pandas` `data frames`. 

I think that if I include the labels I would be able to have `y = [1, 2, 3]`. However, I'm not sure how to sequence the data as numpy arrays because they are currently `Pandas data frames`. 

I'd like to thank you for your patience.

**Comment by jmschrei** [comment]
Is the last column constant for the entire file? Does each file have multiple sequences, or a single sequence? If you want to go from a pandas dataframe to a numpy array you can just do `df.values`. Alternatively you could just load it up using numpy instead of pandas using the `numpy.loadtxt` tool that can easily parse csv files (only grab the columns you need).

For your PCA example, if your input is three dimensions (x, y, z), why are you using a 3 component PCA? You'll just be rotating the data, but I don't think that'll matter if you're learning a full covariance matrix with a multivariate Gaussian distribution.

**Comment by sali45** [comment]
The last column is for the whole file. For each PickUpPhone file it is 1. For each Wave file it is 2, and for each Circle file it is 3. If a gesture counts as a single sequence, then yes, each file is a single sequence. However, there are multiple files of the same gesture, so those would be different sequences. I think I'll stick with using Pandas. As far as PCA goes, I'm kind of a newbie with Machine Learning in general, and I chose a component at random. I'm not sure what the best number of components would be for try-axial data. If you know what I should make it, that would help me a lot. Please let me know if you have anymore questions, and again, thanks for the help. I really appreciate it.

**Comment by sali45** [comment]
Actually, the training value passed in is already a NumPy array so that part is fine.

**Comment by sali45** [comment]
Also, I switched the number of components in PCA to 2. Thanks for pointing that out.

**Comment by jmschrei** [comment]
I would suggest not starting off with PCA until you get a baseline for how good things are without it. No need to over-complicate matters too early on, especially when you only have 3 variables. Once you have the whole thing set up you can re-add it and see if it helps.

**Comment by sali45** [comment]
I'm doing this as part of a project for a professor who wants me to do some sort of feature selection before classification, so I chose PCA. It may not be necessary, but for the purpose of the project, I won't be able to get rid of it. I do understand it is overkill.

I was hoping to get some insight on how to use the labels given in the `CSVs` to label my models. Do you have any insight into how I could do that?

**Comment by jmschrei** [comment]
You probably need to do `X = numpy.array([training])` and `y = numpy.array([0, 1, 2])` in order to index appropriately later on.

`y` just specifies which class it belongs to. If you know that circle is 0, wave is 1, and pickup is 2, you can just decode that afterwards. This is common in machine learning. Conceptually you're on the right track. 

`training` should ultimately be a list (or numpy array) of sequences. If your sequence is 1d, then you'd want to input something like `training = [numpy.array([0, 1, 2, 5, 2, 4]), numpy.array([1, 2, 5, 2]), numpy.array([0, 2])]`. If your sequence is multivariable, then it'd probably end up being `training = [numpy.array([[0, 1], [1, 2], [5, 3], [3, 2]]), numpy.array([[5, 4], [4, 4], [2, 1]]), numpy.array([[0, 2], [5, 7], [2, 7], [8, 4], [9, 6], [8, 6], [7, 3]])`.

**Comment by sali45** [comment]
So currently, my training is already an np array because that is was what the PCA converted it to. When I change `y` to `y = [np.array([0, 1, 2])] I'm not able to do `X[y==0]`. My final question is how does the HMM know which label corresponds to which gesture? How does it know that the `CSV` file contains the label `0` for `circle`? Is it just because I plugged in `0` for the circle model? Basically, I never manipulated the column that contains the labels in the `CSV` file. How else is it supposed to learn that that's its label?

**Comment by sali45** [comment]
One more thing, I get an error for:

`model_circle = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 4, X[y == 0])`

that says: 

` model_circle = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 4, X[y == 0])`

Any ideas on why this happens?

**Comment by jmschrei** [comment]
I think you did not copy the error message correctly. The model will train the HMMs appropriately because you are only feeding in samples that correspond to that label. If it's only exposed to data from a certain class, it can only learn the phenomena for that class.

**Comment by sali45** [comment]
I updated the error. Sorry about that. I'm confident this is the last issue.

**Comment by jmschrei** [comment]
This likely means that X is not formatted correctly. Can you confirm that `X.shape[0] == y.shape[0]`?

**Comment by sali45** [comment]
Ahh, `X.shape[0]` is `1`, and `y.shape[0]` is `3`. When I print `X`, I get

     [[[ 0.00152219  0.07572131]
     [ 0.01675695  0.07837326]
     [ 0.03893698  0.09242237]
     ..., 
     [-0.15572813 -0.03570575]
     [-0.17037947 -0.01243924]
     [-0.17507035 -0.02913436]]]

**Comment by jmschrei** [comment]
Do `X = numpy.array(training)` instead of `X = numpy.array([training])`

**Comment by sali45** [comment]
Hmm, now I get the error:

    IndexError: boolean index did not match indexed array along dimension 0; dimension is 3828 but corresponding boolean dimension is 3

and `X.shape[0]` is `3828`

**Comment by jmschrei** [comment]
I'm guessing that `training` is a single one of your samples instead of a list of three samples.

**Comment by sali45** [comment]
`Training` contains all the `CSV` files that are preprocessed through `PCA`. There are 6 files: 2 for Circle, 2 for PickUp, and 2 for Wave. I pass in all those with a sliding window into the `PCA`. Then I return the result as the `training` parameter.

**Comment by jmschrei** [comment]
Well, it sounds like it may be the concatenation of all of the files, instead of them separately. You need to separate them out so that each element in `training` is a sequence instead of a single observation.

**Comment by sali45** [comment]
So clearly, the issue is in my `PCA` function. I need `training_result` to be a np array where each element is a sequence. However, I've been looking around and can't figure out how to do that.

Here's what I have so far is:

     def windows(files):
           df = pd.DataFrame(columns=['timestamp', 'time skipped', 'x', 'y', 'z', 'label']).set_index('timestamp')
           for my_files in files:
               with open(os.path.join("/Users", "saqibali", "PycharmProjects", "sensorLogProject", "Data", my_files),
              'rU') as my_file:
                  for d in sliding_window(sample_difference(my_file), 50, 25):
                      df = df.append(d)
          return df[['x', 'y', 'z']]

**Comment by sali45** [comment]
Also, is there a way to create an empty numpy array without knowing before hand the shape?

**Comment by sali45** [comment]
I updated my PCA, and I believe it's correct now. Currently my `training` variable looks like:

    [array([[ 0.16289527,  0.07454494],
       [ 0.16186656,  0.08311851],
       [ 0.17932074,  0.09691172],
       ..., 
       [ 0.15882274,  0.31840931],
       [ 0.19720057,  0.30242388],
       [ 0.16924658,  0.29103102]]), array([[ -6.90545189e-02,  -1.20990685e-01],
       [ -6.66923597e-02,  -1.25727965e-01],
       [ -6.47374454e-02,  -1.28292835e-01],
       [ -6.65389504e-02,  -1.23565599e-01],

My HMM file is such:

    def hidden_markov_model(training, test):
        X = np.array(training)
        y = np.array([0, 1, 2])

        model_circle = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 4, X[y == 0])
        model_wave = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 4, X[y == 1])
        model_pickup = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 2, X[y == 2])

        model = BayesClassifier([model_circle, model_wave, model_pickup])
        Z = model.predict(test)
        numpy.savetxt("FILENAME.csv", Z.reshape(1,-1), fmt='%d', delimiter=",")

I get the traceback:

     Traceback (most recent call last):
      File "/Users/saqibali/PycharmProjects/sensorLogProject/Classification/HMM.py", line 18, in <module>
    hidden_markov_model(principal_components()[0], principal_components()[1])
      File "/Users/saqibali/PycharmProjects/sensorLogProject/Classification/HMM.py", line 10, in hidden_markov_model
        model_circle = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, 4, X[y == 0])
    IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 3

**Comment by sali45** [comment]
OK, so I fixed it by removing 3 files so that there is 1 file per label.

**Comment by jmschrei** [comment]
Great! Good luck!
