### ISSUE TITLE
Pomegranate slows down when accessing it frequently

### ISSUE THREAD

**Issue by ArtemiyFirsov** [jmschrei/pomegranate#330]
Hello!

I have an application, that uses pomegranate **GeneralMixtureModel** based on 32 **MultivariateGaussianDistribution** (i.e., GMM). My application gets a model and scores 1 feature vector **100 times per second** in a thread. However, if I have 3-4 threads of such scoring, i.e. about 300-400  **log_probability** function calls per second, pomegranate starts to slow down linearly (CPU is not 100% loaded, has 8 cores). 

This is not an intended behavior. Is this a known issue or maybe smb can explain me, why such situation happens?

**Comment by jmschrei** [comment]
If you have only one feature, you should probably use `NormalDistribution` instead of `MultivariateGaussianDistribution`. I have noticed that BLAS threads and joblib threads can frequently collide and reduce performance, maybe try adding this to the top of your script:

```python
import os
os.environ['OMP_NUM_THREADS'] = '1'
os.environ['MKL_NUM_THREADS'] = '1'
```

Let me know if that helps.

**Comment by ArtemiyFirsov** [comment]
@jmschrei sorry, i meant 1 vector of features). I have 26 features. Thank for suggestion, but, unfortunately, that didn't help.

**Comment by jmschrei** [comment]
Ah, got it. Can you show me the exact code that you are running, or at least a minimally reproducing example?

**Comment by ArtemiyFirsov** [comment]
I do something like below:
```
while not stop:
	data = data_queue.get()
	features = extract_features(data)
	scores = np.array([np.sum(gmm.log_probability(x)) for gmm in gmms])
	process_scores(scores)
```
So, I have data_queue, which is updated approx. 100 times a second. I also have a list of gmms, and I score every gmm on that data. Than I somehow process this scores.

**Comment by jmschrei** [comment]
Can you show me how you would parallelize this? What are the dimensions of `x`?

**Comment by ArtemiyFirsov** [comment]
@jmschrei x is 26-dim, I do not parallelize this. Alike piece of code is running in a single thread. And I have multiple thread, that do exact the same job for different audio streams.

**Comment by ArtemiyFirsov** [comment]
@jmshrei, also there is one more problem, that may be linked with above - pomegranate performs much longer comparing with sklearn on amounts of data more 1000 objects (training and scoring). However, on small, it performs better.

**Comment by jmschrei** [comment]
Hi @ArtemiyFirsov. It's difficult for me to determine what exactly you mean in either of your comments given how detail sparse they are. I can't really help you if I don't understand exactly what's happening.

For the first issue, are you saying that you are running many python processes and that your computer slows down as you increase the number of processes? Is this done using something like joblib/multiprocessing, or by running many python programs from the command line? If you're trying to run many THREADS on a single python process without releasing the GIL, you will see increasingly poor performance regardless of the program because the GIL will prevent more than one thread from running. Either way, that doesn't sound like a pomegranate issue if you aren't using the internal parallel processing tools. If they are all separate processes the problem could be that you don't have enough cores in your computer? I'd need more details on what exactly you are doing.

With regards to comparison with sklearn, is it possible for you to provide more details? What do you mean 1000 objects? Do you mean 1000 components in the mixture, 1000 different mixtures, 1000 samples, a single sample with 1000 dimensions? What is "much longer"?

**Comment by ArtemiyFirsov** [comment]
@jmschrei thank you for your reply. I am using threads, but I find it strange that function execution slows down, as I do not see such a behavior in other functions. Executions time linearly depends on the amount of call to that function (or thread count). 

In the second issue I mean 1000 samples with 26-dims. I didn't measure the exact time,  but I guess its 3-5 times slower.

**Comment by jmschrei** [comment]
Can you provide some minimalistic code samples for these cases?
