### ISSUE TITLE
Negative improvement 

### ISSUE THREAD

**Issue by tryfonch** [jmschrei/pomegranate#363]
Here is the log of my training:
```
model.fit(train_set.data, verbose = True, stop_threshold = 1e-4)
[1] Improvement: 43853.266102309935     Time (s): 0.101
[2] Improvement: 474.0448775529185      Time (s): 0.09901
. . . .
[37] Improvement: 49.88911758163886     Time (s): 0.101
[38] Improvement: 60.8109025786689      Time (s): 0.101
[39] Improvement: -133.24445560177992   Time (s): 0.102
Total Training Improvement: 45486.21092751292
Total Training Time (s): 4.0442
```

As you can see the `Improvement ` at the last iteration is negative. Obviously that is less that the `stop_threshold` so the training will naturally stop.

What is the interpretation of that though? Does it mean that the model is not trained or is trained poorly? Does it mean something else?

**Comment by jmschrei** [comment]
It doesn't mean that the model is trained poorly. I've seen this fairly frequently, typically after many iterations of training, where the negative is only a small fraction of the total improvement. I've interpreted it to mean that the model was essentially in a tight local optima and took a step that was too large.

**Comment by tryfonch** [comment]
@jmschrei Thanks! Do you think that in similar cases (i.e. negative improvement) it would be better to change the initial parameters (e.g change the emission distributions) ?

**Comment by jmschrei** [comment]
Not necessarily. I don't think that stopping on getting a negative improvement is a bad thing, particularly when it's such a small amount (45486 total improvement versus -133 at the end, remembering that this is on a log scale). I have wanted to add in callbacks so that at the end of each iteration you save the model, for instance, so you could just load up the parameters for model 38 instead of being stuck with 39.

**Comment by tryfonch** [comment]
That would be very useful to be able to check the parameters estimated per iteration. 

Regarding the training I have one last question. When you fit a list of samples(n,d) (eg. 10 samples each with shape (20,5) ) how is the model trained in simple words? Does it train for all samples per iteration in the order given or is there a random selection of the samples per iteration?

I am trying to fit time series models in windows of 20 observations and 5 variables and I am not sure whether my input is in the right form. My input is a list of time ordered samples ( i.e. each sample is shifted by one position from the next one). Is HMM appropriate for modeling the above?

**Comment by jmschrei** [comment]
The model is trained by aggregating sufficient statistics from each sample, and then adding them together for a model update. This means that (1) all samples are used each iteration, unless a different batch size is set and (2) the ordering of samples doesn't matter, since the aggregate sufficient statistics are being used (this is similar to how calculating a mean is invariant to the ordering of numbers). 

If you have 10 sequences, where each sequence has 20 observations and each observation has 5 features, then you would want to pass in a LIST of 10 numpy arrays, where each array has shape (20, 5). Each numpy array corresponds to a sequence. 

I don't know why you are feeding in these windows instead of passing the full sequence in. What is the output you are expecting? If you're trying to train an estimator to take in a window of a sequence and predict a value, a HMM is not the right model. If you are trying to tag each observation in a sequence according to some hidden (latent) state, a HMM is the right model.

**Comment by tryfonch** [comment]
@jmschrei  thanks!
