### ISSUE TITLE
Slight length inconsistency in observations, between HMMs with "viterbi" and "map" algorithms

### ISSUE THREAD

**Issue by Komodovaran** [jmschrei/pomegranate#367]
Minor bug/weird inconsistency.

Having set up a HMM model e.g. like so

`HiddenMarkovModel.from_samples(dist, n_components=4, X=obs)`

and fitting it with the viterbi algorithm
`hidden_states = best_model.predict(obs, algorithm = "viterbi")`

the very first index will always be the `n_components`, and to avoid errors when e.g. merging back into the input dataframe, one must cut off the first point of the series, like
`hidden_states = hidden_states[1:]`

This does not happen with the "map" algorithm.

**Comment by ishouldbedany** [comment]
I've noticed this as well. I think this happens because the Viterbi decoding algorithm finds the best path through the model, and it always starts on the `model.start` State. 

So, the first value you see in your vector is not `n_components`, but rather the index of the automatically created `model.start` state in the model's list of states . This index is always equal to the number of components because  `model.start` is appended to the end of the list of states you pass to the model.

**Comment by jmschrei** [comment]
@ishouldbedany is correct. The main reason is because the MAP algorithm will always return the best path through the states that have emissions, and ignore silent states. The viterbi path may go through several silent states (since it is returning the best single path), but there is no clear analog in the MAP estimate (since it is returning the sum of all paths). The start state is a silent state, so it doesn't get reported by MAP.

**Comment by jmschrei** [comment]
I'm going to mark this as resolve, please re-open or open a new issue if you have further questions!
