### ISSUE TITLE
Add model comparison methods

### ISSUE THREAD

**Issue by wcbeard** [jmschrei/pomegranate#372]
It would be nice to have some built in way to compare hmm models, like AIC and BIC, or whatever other metrics are recommended.

**Comment by andy6975** [comment]
Hi! I am new to open source and would like to work on this issue, if it's still open. I really want to contribute to this project so kindly don't mind me commenting on many issue which I found interesting to work on. Thank you so much!

**Comment by jmschrei** [comment]
A built in way would be the log probability of the model on a validation set. You'd just want to do `sum(model.log_probability(sequence) for sequence in data_set)` or each one of your models. If you want to add a penalization based on the complexity you would have to manually calculate that, though, but it shouldn't be too difficult since you know the number of states and the transition matrix size.
