### ISSUE TITLE
Training a HMM with multivariate Gaussian distributions gets dimensionality of parameters wrong

### ISSUE THREAD

**Issue by joshdorrington** [jmschrei/pomegranate#387]
I have provided a minimal version of the task I'm trying to perform, but the output has wrong dimensionality. I have tried explicitly passing parameters to MultivariateGaussianDistribution as well, but that shows the same problem.

```
import numpy as np
from pomegranate import *

data=np.array([[2.0,3.0],[3.0,7.0],[1.0,8.0],[2.0,8.0],[2.0,4.0],[3.0,6.0],[1.0,4.0],[2.0,5.0]])

GMMHMM=HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=3,X=data)

GMMHMM.states[0].distribution.d #should be 2d but is 1d

GMMHMM.dense_transition_matrix() #should be 3x3 but is 5x5
```

**Comment by jmschrei** [comment]
Howdy. Your data input should be 3 dimensional, formatted as (n_samples, n_length, n_dimensions). Essentially, you're passing in an array of samples, where each sample has a length and a dimensionality. This is because you're typically fitting to many samples, not one. pomegranate thinks that you are passing in many samples of length 2, which is why it thinks it's a univariate model. You can amend this with the following:

```
data=np.array([[[2.0,3.0],[3.0,7.0],[1.0,8.0],[2.0,8.0],[2.0,4.0],[3.0,6.0],[1.0,4.0],[2.0,5.0]]])
```

The transition matrix is 5x5 because all models have a built in start and end state, even if you don't explicitly use them. The silent states are the last states in the model, so if you select the first 3 rows and columns of that matrix you should get what you're looking for-- you can confirm this is right by looking as `GMMHMM.states` and seeing the last two have no probability distribution.

**Comment by joshdorrington** [comment]
...Well I should learn to read the docs more thoroughly. Thank you for your clarification
