### ISSUE TITLE
GPU speed up?

### ISSUE THREAD

**Issue by cyberyu** [jmschrei/pomegranate#418]
Hi folks.   First thanks for providing this wonderful package.  I have used it for 3 months and I immediately loved it.   Currently I am stuck with the efficiency of Bayesian Network (I use BN for variable selection so I need to go through all the possible variables and rank their information gains).  Though the speed is already much better than the other Python package I tried before, I wonder whether possible to improve the efficiency further using GPU computation?   Do you guys have plan to push out GPU extension?  Many thanks!

**Comment by jmschrei** [comment]
Howdy!

I'm glad that you like the package. Keep in mind that the default BNSL algorithm is a greedy approximation, not the exact algorithm. 

There is an algorithm that can use BLAS / GPUs for structure learning, but it is inefficient when the number of parents can be large. You can potentially get orders of magnitude speed ups on small numbers of variables / parents, but orders of magnitude slower on larger number of variables / parents, which is the typical use case.

While I did publish some work on structure learning that is included in pomegranate (the stuff on constraint graphs), I have since moved away and am not that familiar with alternative ways to make use of BLAS / GPUs. If you have a resource you'd like to see implemented, that would help a lot in determining if I can add it.

**Comment by jmschrei** [comment]
I'm going to close this for now, but feel free to re-open if you have further questions.
