### ISSUE TITLE
How to git start probability vector π and a transition probability matrix A 

### ISSUE THREAD

**Issue by asd3427** [jmschrei/pomegranate#449]
Hello I am a student who recently learned that HMM needs to use python to complete an HMM model training, but I have a problem that my data is str type I do not know how to get start probability vector π and a transition probability matrix A. How can I solve this problem? Does the function inside pomegranatehelp me solve this problem? I uploaded my data. Please help me.
Sorry for my poor English.......
[hmmData.txt](https://github.com/jmschrei/pomegranate/files/2054540/hmmData.txt)

**Comment by jmschrei** [comment]
Hello!

If you use `model.dense_transition_matrix()` you will get the transition matrix, with the rows and columns ordered according to the states in `model.states`. Note that the ordering may change when compared to how you added them because there is an internal topological sort that is done.

pomegranate has explicit start and end states, so if you're looking for the start transitions it'll be `model.dense_transition_matrix()[model.start_index]`. Likewise if you're looking for ending probabilities (and utilize the end state in your model) it'll be `model.dense_transition_matrix()[:,model.end_index]`.

**Comment by asd3427** [comment]
Thanks I will try 😂

**Comment by asd3427** [comment]
I have seen all the examples but I still don't know how to use   `model.dense_transition_matrix() `

I tried to pass in my data but I get an error. Is there any example for me?
still  Sorry for my poor English.......

> from pomegranate import *
> import random
> import numpy as np
> with open ('hmmData.txt') as f:
>     data = f.read()
>     f.close()
> data=data.split('\n')
> 
> l=[]
> for i in data:
>     n=[]
>     for a in i:
>         n.append(a)
>     l.append(n)
>     
>     
> state = np.array([1,2,3])
> model = HiddenMarkovModel()
> model.states=state
> model.dense_transition_matrix(l)
>

**Comment by jmschrei** [comment]
Your HMM has nothing in it. Every HMM example either builds the structure manually (through `model.add_states` and `model.add_transition`) or learns it directly from data (`HiddenMarkovModel.from_samples`). Are you looking at an example that doesn't do either one of these?

**Comment by asd3427** [comment]
sorry i will see the example again !!!thanks for  your answer ^^~

**Comment by asd3427** [comment]
Jmschrei sorry i am come again i still don't know how to use pomegranate to get the probability i need ,is there any example can teach me how to use get it's????

**Comment by asd3427** [comment]
Sorry for this late reply. According to your example I have completed this HMM training. Thank you

**Comment by jmschrei** [comment]
Great!
