### ISSUE TITLE
 How does BayesianNetwork handle large data set

### ISSUE THREAD

**Issue by wooboo0954** [jmschrei/pomegranate#474]
Hi, I am try to use BayesianNetwork.from_samples, but it seems that the sample is too large then the python breaks down, below is my code:

        bn = networkx.DiGraph()

        a = (0,)
        b = (1,)
        c = (2,3)
        d=(4,5)

        bn.add_edge(a,b)
        bn.add_edge(a,c)
        bn.add_edge(a,d)
        bn.add_edge(b,c)
        bn.add_edge(b,d)
        bn.add_edge(c,d)

        model = BayesianNetwork.from_samples(data_sampled, algorithm='exact',constraint_graph=bn)

When the data set contains more than about 80000 samples, the python dead. PC's memory is 32G, and it is not fully ocuppied in the tests.  So, does the from_samples method has  a limitation on the sample size?

Then I try an alternative way as this: Use from_samples on a small size data set(call it dataset_1) first to bake a model, then use fit method to fit batches of new smaple repeatly until the end. However, it comes up with another problem, as some states do not seem in the dataset_1, then in the following batch fitting process, it gives the following error:   pomegranate.distributions.DiscreteDistribution.summarize(pomegranate\distributions.c:26479)
KeyError: 2

I can not figure out how to handle the large data set and hope some one can help.

**Comment by rzu512** [comment]
nope... memory usage increases like 1% per seconds, even if I set `batch_size` to 1000.
```python
 model = pg.HiddenMarkovModel.from_samples(
        pg.DiscreteDistribution, n_components=2, X=data, batch_size=1000)
```

**Comment by jmschrei** [comment]
Howdy

@wooboo0954 I can't reproduce your issue without more code or an example data set. I created the following example based on what you provided but it finished in a few seconds:

```
data_sampled = numpy.random.randint(0, 10, size=(80000, 6))

bn = networkx.DiGraph()

a = (0,)
b = (1,)
c = (2,3)
d = (4,5)

bn.add_edge(a,b)
bn.add_edge(a,c)
bn.add_edge(a,d)
bn.add_edge(b,c)
bn.add_edge(b,d)
bn.add_edge(c,d)

model = BayesianNetwork.from_samples(data_sampled, algorithm='exact',constraint_graph=bn)
print model.structure
```

@rzu512 can you provide more details as well? Are you passing in 40,000 univariate sequences of length 30,000, or one sequence with 30,000 dimensions? Your data by itself is taking up almost 10G, so that's probably not helping. batch_size will only help when your data is a numpy memory map, because otherwise you've loaded the data into memory already anyway.

**Comment by rzu512** [comment]
30,000 sequences. 
Each sequence has a length 40,000. 
Each value in the sequence is a boolean.
Since numpy use a byte to hold a boolean, the total size is:
    30,000*40,000**1*1e-9 = 1.2GB
Computer has 16GB memory.
I also tried to disable gpu, but memory usage is still too much.
I can use another machine with more memory but no gpu.
What is the expected memory usage if I use batch_size?

**Comment by jmschrei** [comment]
pomegranate will convert all numerics to 64 bit floats because I didn't have time to implement multiple types of dtypes in the underlying cython code. The expected memory usage should be the model size + the size of the batch, which is the number of sequences. 

I tried with some sample code and don't see the memory increasing steadily during runtime after the data is converted to 64 bit floats, so I suspect this conversion to 64 bit floats is what's causing the memory explosion. You can pass in `verbose=True` to see if the model is training as your memory gets used up (indicating a memory leak) or if it hasn't started yet (indicating the conversion). Sorry about the inconvenience.

```python
data = numpy.random.randint(2, size=(30000, 4000))
model = pg.HiddenMarkovModel.from_samples(pg.DiscreteDistribution, n_components=2, X=data, batch_size=100, verbose=True)
print model.d
```

You're likely to see faster speeds if you use a BernoulliDistribution instead of a DiscreteDistribution for binary data, btw.

**Comment by rzu512** [comment]
It is the conversion to 64bit floats that makes pomegranate uses more memory than I expect.
After running the program on another machine with 64Gb memory, it works now and uses about 18 Gb memory if I fit for 2 hidden states:

```
$ cat 06_hmm.log 
06_hmm.py:12: RuntimeWarning: invalid value encountered in true_divide
  batch_size=5000, verbose=True, n_jobs=12)
06_hmm.py:12: RuntimeWarning: invalid value encountered in less
  batch_size=5000, verbose=True, n_jobs=12)
[1] Improvement: 666925178.9412812      Time (s): 74.59
[2] Improvement: -6.666779518127441e-05 Time (s): 75.38
Total Training Improvement: 666925178.9412146
Total Training Time (s): 235.7574
```
I assume the warnings are harmless.

**Comment by jmschrei** [comment]
I'll look into it tonight just to confirm. If you're getting reasonable predictive performance I'd assume they're harmless too.

**Comment by jmschrei** [comment]
Latest commits should fix the RuntimeWarnings.

**Comment by wooboo0954** [comment]
@jmschrei Thanks for the quick responce. Adding more states may reproduce the problem: 

data_sampled = np.random.randint(0, 1000, size=(80000, 6))

bn = networkx.DiGraph()

a = (0,)
b = (1,)
c = (2,3)
d = (4,5)

bn.add_edge(a,b)
bn.add_edge(a,c)
bn.add_edge(a,d)
bn.add_edge(b,c)
bn.add_edge(b,d)
bn.add_edge(c,d)

model = BayesianNetwork.from_samples(data_sampled, algorithm='exact',constraint_graph=bn)
print model.structure

Then I got this on conda:
Kernel died, restarting

I think my problem is not cause by memory explosion as the memory was not fully ocuupied when this happend.

**Comment by jmschrei** [comment]
This is likely too late for you but the problem is likely that using values between 0 and 1000 will create massive conditional probability tables. Marginal distributions will have 1000 values, conditional tables with a single parent will have 1000**2 values, two parents will have 1000*3 values, etc. This is likely a memory error.
