### ISSUE TITLE
[QUESTION] Training HMM when having Hidden states and Observations available

### ISSUE THREAD

**Issue by emilmirzayev** [jmschrei/pomegranate#479]
Hi there! Just discovered this package working on my study project. 
I read the docs and I must admit that I did not understand some parts of it. That's why I am asking this question. Lets say we have:
- An observation sequence of O = {0, 1, 2, ... o} which can be continuous
- A hidden state sequence of S = {s1, s2, s3, .... sn}
I do not have either transition matrix A, emission matrix B or start probabilities P. I should use Baum-Welch algorithm to train my data. Is it possible to train the model and getting A, B, P values having just observations and states? if yes, how I can do it?

best,
Emil

**Comment by jmschrei** [comment]
Sorry for the late reply to this.

There are a few situations in which you can train a HMM. The first is when you only have  a sequence of observations and know the number of hidden states, but not their emissions or transitions or the labels of the observations. This involves assuming a dense network and learning transitions and emissions jointly. You can do this in pomgranate using `HiddenMarkovModel.from_samples(NormalDistribution, 3, X)` for a model with 3 states that are univariate Gaussians (of course substitute in your own distribution or number of components as necessary). 

The next situation is where you know the structure of the network but not the emissions or the values of the non-zero probability transitions (zero probability transitions are those that don't exist in the structure) or the labels for your observations. This can be done by building the HMM node by node and edge by edge using the `add_node` and `add_edge` methods, and then calling `bake` once the structure is finalized, and lastly `fit` to fit to your data.

The last case is either of the above but you do have labels for the observations. When you don't have labels you use a form of structured EM called the Baum-Welch algorithm to iteratively train your model. When you do have labels you can use simple MLE estimates to derive the parameters. You can do this by passing in a sequence of state labels (the string names) and specifying `algorithm='labeled'`. 

Bonus round: You can do semi-supervised learning where you have the labels for all observations in a sequence for some, but not all, sequences. In this situation you pass in `None` instead of a list of labels for that sequence. Some people have reported that there is a bug with that, which I'm looking into, but conceptually semi-supervised learning is a thing.

Let me know if that answered your question.

**Comment by emilmirzayev** [comment]
Hi Jacob,

thank you for your reply. I understand that you might've been quite busy nowadays :)
I will explain my use case to you in detail. I have a main meter in my house which captures the overall house electricity consumption and also a sub-meter plugged to my fridge. I am trying to build a model which can say when I switch on the fridge (when it starts working and so on) based on main meter consumption change.
For that I want to use HMM. The state of the art of energy disaggregation. Fridge consumpion is somewhat discrete. I will use PMF to create lets say 3-4 states. On the other hand I will have main meter consumption. 
My hidden states would be those states of fridge, and observations will be main meter consumption.
As far as I understood from your reply, it is possible to train a model using Pomegranate. Yet, the technical part was unclear to me. Can you please explain it a bit more simpler way when you have some time these days?
best,
Emil

**Comment by jmschrei** [comment]
Hi Emil

This may be too late for you, but here's an answer:

Your hidden states would be the 3-4 fridge consumption states (to my understand this is what you're trying to predict). Each state would have a probability distribution, the emission, that is what you expect the main meter consumption to look like.

Implementation wise, if you have some very long single sequence of main meter consumption values that you'd like to cluster, `X`, where X.shape = (number_of_observations,),

```
from pomegranate import HiddenMarkovModel
from pomegranate import NormalDistribution

X = ... your vector of main meter consumption values ...

model = HiddenMarkovModel.from_samples(NormalDistribution, 3, X)
```

This will give you a HMM with three hidden states. You'll need to identify which states correspond to the different fridge consumption values. If you think there might be other phenomena occuring in the main meter consumption, this is a bad idea because the clusters might correspond to those phenomena rather than the fridge states. 

What type of data do you have?
