### ISSUE TITLE
Positive values in forward matrix when training HMM from_samples

### ISSUE THREAD

**Issue by sabjoslo** [jmschrei/pomegranate#483]
I'm just learning about HMMs so I suspect I'm missing something obvious here:

I'm trying to train an HMM using `from_samples` on sequences of continuous data that's bounded between 0 and 1. I've specified that the underlying distribution should be normal. When I look at the `log_probability` of my models, I'm getting values *above* 0, up to around 20 for some sequences:
```
>>> hmm = pomegranate.HiddenMarkovModel().from_samples(pomegranate.NormalDistribution, n_components = n, X = X)
>>> hmm.log_probability(X[0])
20.834043926019838
```

When I looked further into it, I realized that there were positive values in the output of `model.forward(x)` for some of the sequences in my data.

From everything that I've read, I understand that the `.forward()` method should output a matrix where each cell i, j contains the log probability of observation i being in state j. Since I'm expecting log probabilities, I'm confused to see positive values.

Am I misunderstanding something basic, and/or using the API incorrectly?

**Comment by jmschrei** [comment]
Howdy

You're not misunderstanding anything. While log probabilities are typically negative, they can be positive for the same reasons that probabilities can be above 1. Consider a uniform distribution between 0 and 1. The probability of any point between 0 and 1 will be 1. A uniform distribution between 0 and 10 will yield a probability of 0.1 for any point in that range. Correspondingly, a uniform distribution between 0 and 0.1 will yield probability estimates of 10 for any point in that range. Since your data is distributed between 0 and 1 you likely have a sharp spike in probability that exceeds 1 (causing the log probability to be positive).

Let me know if you have any other questions.

**Comment by sabjoslo** [comment]
Hey, thanks so much for the super-quick reply! Just to make sure I understand:

For continuous distributions like the normal, the forward algorithm calculates the joint probability of each state j with the history of evidence over the support of the entire normal, and then evaluates the joint distribution at the point i. Since these are probability density functions, evaluating them at any single point can turn out "probabilities" above 1.

High values in the forward matrix either mean that that observation is really likely given the model or that the normal is constrained due to constraints on the data (which applies here). So the surprisingly high log probs don't necessarily indicate a good model--just a constrained space of observations.

**Comment by jmschrei** [comment]
Yes that’s correct. I would be wary to interpret the probability of a
sequence given the model by itself regardless of how big or small it is,
but rather how it compares to other sequences. If 1000 random sequences all
produce lower probabilities than the given one, the given one seems very
likely given the model, even if all sequences had high probabilities.
