### ISSUE TITLE
Fitting a continuous multivariate HMM from labeled data

### ISSUE THREAD

**Issue by sdk29** [jmschrei/pomegranate#485]
Hi,

I'm interested in fitting a Multivariate Gamma HMM from labeled data. The observations are from one long time-series, so right now I'm treating it as a single sequence.

I have a dataset with observations that are 6-dimensional from independent Gamma distributions. 
```
X: (N,6) numpy array of dtype float
    N is the number of samples and 6 is the number of features.
```

The dataset also includes labels for the 4 hidden states. 
```
labels: (N,) numpy array of dtype int 
    Labels from the set [0,1,2,3].
```

The documentation and tutorials are great for fitting an event HMM to unlabeled data and for a multivariate GMM, but I'm having a surprisingly difficult time with a continuous multivariate HMM.

It seems that the `from_samples()` method is the best to use
```python
model = HiddenMarkovModel()
model.from_sample(distribution=GammaDistribution, X=X, labels=labels, algorithm='labeled')
```
but I get TypeError: from_samples() takes at least 3 position arguments (1 given).

Everything is so nicely set up, I'm sure there's an easy solution I'm missing. Any suggetions? Hopefully this will help someone else looking to fit a continuous multivariate HMM from labeled data.

Thanks

**Comment by jmschrei** [comment]
Your input is supposed to be a list of sequences that you want to train on. If the shape of your input is (n, 6), it is assuming you are passing in n sequences all of length 6. You should try `model = HiddenMarkovModel.from_sample(distribution=GammaDistribution, X=[X], labels=[labels], algorithm='labeled')`.

**Comment by sdk29** [comment]
Thanks. I've added your suggestion as
```
model = HiddenMarkovModel.from_samples(distribution=GammaDistribution, 
                                       n_components=4, 
                                       X=[X], 
                                       labels=[y], 
                                       algorithm='labeled')
```
and now I get ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Is it correct that n_components=4 for a model with 4 hidden states?

**Comment by jmschrei** [comment]
Can you copy/paste the full error message? It'd be useful to see if this might be an issue with gamma distributions, as they are relatively less used, rather than HMMs. You're correct that n_components=4 is a model with 4 hidden states.

**Comment by sdk29** [comment]
```
  File "pomegranate\hmm.pyx", line 3600, in pomegranate.hmm.HiddenMarkovModel.from_samples
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I've been digging and it looks like it might be a problem with the labels here. What should the labels be, besides a long list? Any particular type? 

Right now the labels are floats from the set [0,1,4,5], i.e. each of the N samples has a label of 0, 1, 4, or 5. I imagine this isn't the correct way to pass the labels.

**Comment by jmschrei** [comment]
The initial way was to have the labels correspond to the name of the states. If you're doing `from_samples` there is no name yet, and so it should automatically name the states according to the label set that you give it.

When you say "each of N samples" you mean each of the observations, right? That should be correct. They labels should be of shape (n_sequences, n_observations) where the data is of shape (n_sequences, n_observations, n_features).

Can you try running it without labels? That might help track down where the problem is coming from.

**Comment by sdk29** [comment]
If I remove the labels it executes fine.

The problem seems to be iterating over the labels. In line 3600 of hmm.pyx there is a check to make sure the label of each sequence does not equal None. 
```
X_ = [x for x, label in zip(X, labels) if label != None]
```

Here, X is a list of length 1 and labels is a list of length 1, corresponding to the 1 sequence. Iterating through the zip(), x is a (N,6) np.ndarray of emission observations and label is a (N,) np.ndarray of state labels.  However, the following error occurs:
```
X_ = [x for x, label in zip(X, labels) if label != None]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
presumably because of the `label != None` check.

I converted the (N,) np.ndarray of labels to a list so that `labels = [[label_1, label_2, ..., label_N]]` and that fixed the issue. Now, x is (N,6) np.ndarray and label is a list of state labels corresponding to each of the N observations in sequence 1.

If I had read the documentation on labels more closely, it is clear that the labels should be a list of sequences. In my case, the length of the list is just 1. However, it also seems like observation labels for a given sequence should be a list, unless the check is wrapped in `np.all(label != None)`. 

Thanks for the help, I really appreciate the quick feedback.

**Comment by jkleckner** [comment]
@sdk29 Can you recommend a check that would prevent others from seeing this problem in the future?

**Comment by jmschrei** [comment]
@sdk29 great, glad it worked for you!

I think that I should issue a warning whenever someone passes in a non-list object as `X` such as a numpy.ndarray, because that typically means that they're passing in a single multi-variate sequence.

**Comment by sdk29** [comment]
I think the documentation is very good. Maybe simply something to the effect of 
```
X : list
    Each item in the list is a sequence, and each sequence 
    is a numpy.ndarray of emission observations...
labels : list
    Each item in the list is a sequence, and each sequence 
    is a list of observation labels...
```

**Comment by stefan-de** [comment]
Hi, 
I'm interested in fitting multivariate time series of binary data, in order to get the hidden states of the process.
Data:
X.shape = (6282, 144) -> 144 features containing only binary data.

Console:
                         X
Out[]: 
                         array([[0, 1, 0, ..., 0, 0, 0],
                         [0, 1, 0, ..., 0, 0, 0],
                         [0, 1, 0, ..., 0, 0, 0],
                         ...,
                         [0, 0, 0, ..., 0, 0, 0],
                         [0, 0, 0, ..., 0, 0, 0],
                         [0, 0, 0, ..., 0, 0, 0]], dtype=int64)


                          X.shape
Out[]:                 (6282, 142)

                          model = pg.hmm.HiddenMarkovModel.from_samples(distribution = 
                                                                                                                pg.BernoulliDistribution,
                                                                                                                n_components = 5, 
                                                                                                                X = [X])

                          model.predict([X])
Out[]:             [0]

Any suggestions?

**Comment by jmschrei** [comment]
Howdy

While your input to HMM fitting functions should be a list of sequences, the input to the inference functions should be a single sequence. Try running `model.predict(X)`. Is there an error raised or just nothing returned?

**Comment by stefan-de** [comment]
X.shape
Out[65]: (6282, 142)

model = pg.hmm.HiddenMarkovModel.from_samples(distribution = pg.BernoulliDistribution,
                                              n_components = 5, 
                                              X = [X])


print(model.predict(X))
Warning: Sequence is impossible.
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,.................

What do you mean by single sequence in this case? Since one observation contains 142 features and I would like to uncover all hidden states of 6282 observations?

**Comment by jmschrei** [comment]
Sorry that you're running into issues. The warning means that the sequence you've passed in is not possible according to the HMM that was learned. Potentially this is because your training data has 0s in all one column but the test data has a 1 there. If you can post a minimal example of this error here I can try to debug it.

**Comment by jmschrei** [comment]
You can also try using a NormalDistribution instead of a Bernoulli one to see if the bug is in the distribution object. Theoretically it should be very similar to fit a Normal and a Bernoulli distrbution because a NormalDistribution will learn a mean and variance such that the densities at 0 and 1 are the same relative heights.

**Comment by stefan-de** [comment]
There is no split in my data, I use the same date for both fitting and predicting.
I would like to compare both the Gaussian and Bernoulli HMM.

Thank you for your help!

Data:
[liste.zip](https://github.com/jmschrei/pomegranate/files/3970307/liste.zip)

prediction = normal_model.predict(X)

normal_model = pg.hmm.HiddenMarkovModel.from_samples(distribution = pg.NormalDistribution,
                                              n_components = 5,
                                              X = [X])

print(normal_model.predict(X))
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,..........

**Comment by jmschrei** [comment]
I was able to reproduce the issue with both Bernoulli and Normal distributions. As you may have noticed, the problem arises because the parameters of the distributions become NaN. This happens because pomegranate is ungraceful when certain components of the model cluster with no examples or when certain parameters (like standard deviation) become 0. This happens when your data is structured in a way that doesn't support the number of clusters you're trying to fit to it. I was able to resolve the issue by adding even a tiny variance to the data set (`X += numpy.random.normal(0, 0.0001, size=X.shape)`). A more elegant way for you would likely be to write a custom distribution that is similar to a NormalDistribution or BernoulliDistribution object except has a minimum variance or probability for each element. Sorry about the inconvenience.

**Comment by stefan-de** [comment]
1. Through adding some gaussian noise as you suggested I was able to fit a model with gaussian emission but when I'm trying to fit and predict a gaussian model with e.g. 20 states I get  -1s too.

2. Apart from that I suspect that a gaussian model is far away from being aquivalent to a bernoulli model.

3. Have you a susggestion on how to implement a custom bernoulli distribution in order to being able to model multivariate binary time series data.

Thank you in advance!

**Comment by luckkyjoyce** [comment]
Hi, I am wondering, have you figure out how to implement the model on the multivariate binary time series data? I met the same issue. @stefan-de

**Comment by jmschrei** [comment]
I'll come back to this issue after my paper deadline on the 30th.

**Comment by stefan-de** [comment]
@luckkyjoyce  unfortunately not.
