### ISSUE TITLE
MDL algorithm

### ISSUE THREAD

**Issue by Geldren1** [jmschrei/pomegranate#486]
Hello Jacob,
What MDL algorithm is used? I understand there are several and I have not had much success investigating MDLs for graphs/BBNs. Could you please point me in the right direction?
Many thanks

**Comment by jmschrei** [comment]
Howdy

My understanding is that minimum description length (MDL) is not an algorithm but an objective function. The goal is to evaluate "how good" a certain graph structure is, and MDL does this by seeing how well it fits the data but penalizes it based on its complexity, because of course a fully dense graph would fit the data the best. It's been a fairly standard objective function for Bayesian network learning. What types of resources are you looking for? I'd try just googling papers on learning Bayesian network structure or on MDL itself.

**Comment by Geldren1** [comment]
Figured it out. It has two parts, the first calculates the length of the model in bits (a function of the number of parameters) and penalises it for bigger models. The second calculates the length of the data as represented by the model, again in bits, the shorter the better.
Helen   On ‎Wednesday‎, ‎29‎ ‎August‎ ‎2018‎ ‎18‎:‎35‎:‎47‎ ‎BST, Jacob Schreiber <notifications@github.com> wrote:  
 
 
Howdy

My understanding is that minimum description length (MDL) is not an algorithm but an objective function. The goal is to evaluate "how good" a certain graph structure is, and MDL does this by seeing how well it fits the data but penalizes it based on its complexity, because of course a fully dense graph would fit the data the best. It's been a fairly standard objective function for Bayesian network learning. What types of resources are you looking for? I'd try just googling papers on learning Bayesian network structure or on MDL itself.

**Comment by jmschrei** [comment]
Great!
