### ISSUE TITLE
BayesianNetwork.sample not implemented (?)

### ISSUE THREAD

**Issue by echo66** [jmschrei/pomegranate#500]
Greetings! 

I was trying to use the `sample` method as described in the API but I'm getting the following error

![image](https://user-images.githubusercontent.com/778261/46907227-4c805680-cf07-11e8-976c-d06c66938357.png)

I'm using Fedora 28 and Python 3.6.

**Comment by echo66** [comment]
@jmschrei , is this the correct place to ask? I thought it was because, after looking into the code, it makes (at first sight) no sense for this error to exist because there is actually an implementation for the sample method.

**Comment by jmschrei** [comment]
Howdy

This is the right place to ask. While `sample` is implemented for every other model, there currently isn't an implementation of the `sample` method for Bayesian networks yet. This is because it's a bit more complicated, as one has to find the root node and begin sampling recursively from there. If you'd like to take a stab at it I'd be happy to include the contribution.

**Comment by sashaostr** [comment]
+1

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
