### ISSUE TITLE
Maybe use SSE version of logsumexp

### ISSUE THREAD

**Issue by fgregg** [jmschrei/pomegranate#51]
At least in the HMM, you are spending a lot of time computing the log-sum-exp, I wonder if it would be useful to use a SSE version of that function https://github.com/rmcgibbo/logsumexp

**Comment by jmschrei** [comment]
It's true that a of time is spent in log-sum-exp. However, I've optimized it to be faster than the scipy functions by knowing it's only computing a pair at a time, allowing you to only do one exp instead of two. It also doesn't do any exp in edge cases where it's not needed.

I don't fully understand the SSE version. I'm not opposed to included it if it's faster, but I also don't think I have the time right now to understand how it works. If you could find a good resource for me that explains it, I'd def read it though.

**Comment by jmschrei** [comment]
Closing Please re-open if there is further discussion.
