### ISSUE TITLE
Potential memory-leak when sampling from HiddenMarkovModel

### ISSUE THREAD

**Issue by paulbrodersen** [jmschrei/pomegranate#510]
I run out of memory when trying to generate 100 samples from a HMM on a 16GB machine. 

MWE

```python
#!/usr/bin/env python

import numpy as np
from pomegranate import (
    NormalDistribution,
    State,
    HiddenMarkovModel)

if __name__ == '__main__':

    print('Generating normal distributions...')
    d1 = NormalDistribution(0., 1.)
    d2 = NormalDistribution(1., 2.)

    print("Initialising HMM...")
    s1 = State(d1, 's1')
    s2 = State(d2, 's2')

    # transition probability matrix
    Q = np.array([[0.9, 0.1],
                  [0.2, 0.8]])

    model = HiddenMarkovModel()
    model.add_state(s1)
    model.add_state(s2)

    model.add_transition(s1, s1, Q[0,0])
    model.add_transition(s1, s2, Q[0,1])
    model.add_transition(s2, s1, Q[1,0])
    model.add_transition(s2, s2, Q[1,1])
    model.bake()

    # print(model)

    print("Simulating sequence...")
    samples, simulated_path = model.sample(100, path=True)
```

Tested both under python 2.7.13 and python 3.5.1 using pomegranate version 0.10.0.

**Comment by jmschrei** [comment]
Howdy

Sorry you ran into some trouble. I was able to replicate the issue, and the problem is that you don't have any starting probabilities. You need to add in transitions from `model.start` to either `s1`, `s2`, or both. This should raise an issue when you try to bake the model, but it currently doesn't. 

I also just pushed some changes to GitHub (not on PyPI yet) to sampling procedures you might find helpful. This changes HMMs by allowing you to specify both the number of samples (the first parameter) and the length of the samples when no explicit end state is used (the second parameter). In your case, you would need to specify something like `model.sample(1, 100, path=True)` and that would generate one sequence of length 100, whereas `model.sample(100, 5, path=True)` would return 100 sequences of length 5.

Let me know if you encounter any other problems.

**Comment by paulbrodersen** [comment]
Many thanks for the quick reply. This indeed fixes the problem. 
To prevent this from happening, what about adding the following test at the end of `bake`:

```python
assert numpy.any([a == self.start for (a, _) in self.graph.edges_iter()]), "Need to specify a transition from model.start to at least one other state."
``` 

> Let me know if you encounter any other problems.

I am still having troubles fitting HMMs with multivariate Gaussian emissions to my data (fitting the dimensions individually works beautifully though). So once I have narrowed down the problem some more, I will probably raise another issue (I only came across this issue here because I tried to make some simulated data).
