### ISSUE TITLE
Specifying hidden states and input in from_samples method

### ISSUE THREAD

**Issue by jaspreetpandher** [jmschrei/pomegranate#517]
I want ti try the HMM with different number of hidden states. How do I specify the number of hidden states. It seems that n_components is controlling the number of observable states?

Also, while giving input X for one of the observations, say I have 32 example sequences of length 5 each for training, will my X be a list of length 32 where each element of the list is another list of length 5?

**Comment by jmschrei** [comment]
I'm not sure what exactly you're asking. `n_components` controls the number of hidden states. The observations are the symbols that are being passed in, and the hidden states are the set of distributions that each observation could potentially have come from. 

If your observations are univariate then you should pass in a list of numpy arrays, where each numpy array is of shape (n,) where n is the number of observations. In your case with 32 sequences, X should be a list of 32 numpy arrays where each numpy array has the shape (5,).

**Comment by jkleckner** [comment]
In a somewhat similar vein, `predict_proba()` returns only the non-hidden states but it seems that for continuous models, there is some nonzero probability of being in a hidden state, true?

**Comment by jmschrei** [comment]
I think you mean silent and non-silent states, not hidden and non-hidden. You can't align a silent state to an observation, you can only pass through a silent state on your way to the next non-silent state when you align your observations to states. Because of that, there is a non-zero probability of passing through a silent state, but not to align an observation to one. The forward-backward algorithm returns an expected transition matrix (number of times you pass over each edge in the model) and an expected emissions matrix (probability that each observation aligns to each non-silent state). Both are returned if you use the `forward_backward` method. Only the expected emissions matrix is returned if you use the `predict_proba` method.

**Comment by jaspreetpandher** [comment]
Thanks Jacob :) Reading your reply, I am a little confused about MultiVariate Gaussian distribution now.

Here is my situation :
I have famine scores (discrete values from 1 to 5) and vegetation indices (continuous values). Both these are my observed outputs. I was thinking of assuming that both these follow a Gaussian distribution and hence was going to use the distribution of MultiVariateGaussian. However, from your reply above it seems that the distribution refers to the distribution of hidden states and not observed states? In that case, do I just assume a univariate distribution of hidden states ? Also, is there a way to explore dependence between the 2 kinds of observed states I mentioned above? By dependence, I mean could my model predict the next observed state for famine better given that it knows how vegetation index changes over time?
