### ISSUE TITLE
request - logsumexp as util function and some questions

### ISSUE THREAD

**Issue by itaysason** [jmschrei/pomegranate#518]
Hi, I saw you implemented logsumexp and it is most likely a lot faster than the scipy version (which is very slow). Can I request the following 2 utils function?

- The same as numpy.logaddexp, takes 2 arrays and compute the element wise logsumexp, optionally add "out" similarly to numpy and other features. I am not sure if your version will be faster than numpy, ref - https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.logaddexp.html.

- The same as scipy.misc.logsumexp, takes 1 array and dimensions to sum over, and returns the logsumexp of it, again optionally  add some more features. Here I am sure your function is faster than theirs, ref - https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.misc.logsumexp.html.

BTW Love your package! I use it a lot and build some more complex models using it and it is always faster than what I do, partially because of the logsumexp problem.
-Are you planning on building a more general framework in the future? i.e dynamic bayesian networks? 
-Another small question, is it possible to define a model consisting of several HMM's all having the same states? i.e each HMM will have its own transition probability but all will have the same emission probabilities.

**Comment by jmschrei** [comment]
Howdy

I wasn't sure that my functions were actually faster than scipy so I went ahead and tried adding them to `utils`. As you predicted, it looks like logsumexp is around an order of magnitude faster than scipy when calculating on 100 samples, around the same speed on 1,000 samples, and an order of magnitude slower on 10,000 samples. I'm not positive what this variability is caused by. logsumadd is approximately the same speed as numpy's function. I haven't added in the optional input arguments, and don't plan to unless it's necessary.

Thanks for the positive feedback. I'm not planning on extending the scope of pomegranate significantly past what is there now. I'm mostly focusing on expanding the documentation and making it more flexible so that users can extend it on their own. 

If you want to define multiple HMMs with the same states you can pass the same state objects into multiple HMMs. Because the underlying distributions will be the same objects, training any one of those HMMs will update the distributions for all the HMMs. Is that what you were looking for?

**Comment by itaysason** [comment]
Thank you for your reply,
your util function works great! I wonder why you function becomes slower than theirs on large inputs maybe it is worth checking it out. anyway because my input size is very small this really helps!

about your suggestion with multiple HMM's, this is what I was looking for but the problem is I want to fit with all HMM's. The intuition behind what I need is that lets say we have a list of books, we believe that each word in each book is coming from some topic (topics doesn't change between books), and in each book the distribution and transition between topics is different. So I want to train several HMM's (one for each book) all sharing the same topics.
