### ISSUE TITLE
hmm.bake resetting random seed

### ISSUE THREAD

**Issue by joshdorrington** [jmschrei/pomegranate#525]
I had some issues in some of my scripts that use the pomegranate HMM where arrays that were supposed to be random were coming out the same every time. I managed to track down the cause to two lines in the bake() method of the HiddenMarkovModel:

`numpy.random.seed(0)
 random.seed(0)`

It's not necessarily clear to me what this is for? Is it to make sure that the clusters found for a given dataset are deterministic? If so that seems quite artificial and maybe there should be a flag to turn this on and off?

**Comment by jmschrei** [comment]
I had noticed that the unit tests failed when I removed those lines, and anticipated that it was because the topological sort step had some element of randomness to it. It didn't really make sense to me, but I didn't have time before to look into it.

I decided to look into it tonight and noticed that if I ran a single test that failed after removing those lines, the test would pass. It was only when all unit tests were run that it failed. Long story short, no aspect of the bake function depended on a random seed being set, but there was randomness in the unit tests themselves that was being controlled when I set a deterministic seed.

I have now removed those two lines and set seeds appropriately in the unit tests themselves. If you can build pomegranate yourself, give it a try and let me know if that's working for you.

**Comment by jmschrei** [comment]
Please re-open if this is still an issue.
