### ISSUE TITLE
BayesianNetwork.plot is not passing kwargs into networkx.draw_networkx()

### ISSUE THREAD

**Issue by tmadeira** [jmschrei/pomegranate#526]
I believe `BayesianNetwork.plot` method is not passing its kwargs into `networkx.draw_networkx()` (or maybe it's not using it at all?), so I'm unable to [customize](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.drawing.nx_pylab.draw_networkx.html#networkx.drawing.nx_pylab.draw_networkx) the drawing.

https://github.com/jmschrei/pomegranate/blob/047aec34c9cd2db18ea44edb5eeac1bfee7c49a9/pomegranate/BayesianNetwork.pyx#L244-L281

Is that a bug or am I doing something wrong?

**Comment by jmschrei** [comment]
The bug is in the documentation, not the code. I made the code use PyGraphviz as the backend, which produces very nice visualizations, rather than matplotlib, which produces fairly poor ones. However, it doesn't look like it's as neat to pass in arguments. I've removed the misleading documentation. 

If you want more flexibility in plotting you could try replicating the method in your own function, but including what it is you need. Fortunately it's not a very complicated function.
