### ISSUE TITLE
Fail to update hmm.graph after training

### ISSUE THREAD

**Issue by markzendejas** [jmschrei/pomegranate#54]
The hmm's model.graph's edge weights are not being updated after training.

**Comment by markzendejas** [comment]
@jmschrei I fail to understand your code a little, maybe you can help me. You have both in_transition_log_probabilities and out_transition_log_probabilities. Then these are updated separately in _baum_welch_update, but aren't both of these redudant. The out_transition_log_probabilities from node a to b is the in_transition_log_probabilities from a to b. Isn't it wasteful to do the calculation twice?

**Comment by jmschrei** [comment]
Yes, model.graph pretty much gets discarded after being used as a convenient way to store the graph while you build it. If you need transition probabilities you can use model.dense_transition_matrix(). I should probably make that attribute private so that people don't use it.

They are a little bit redundant. In theory, if we knew where exactly in the out_transition vector our edge was, we could simply copy it to in_transition. However, we don't, because of the sparse matrix representation. It actually takes more time to find the correct spot than to just redo the calculation.

That being said, a possibility is to have a key value store which maps out_transition to in_transition. I haven't experimented with this. However, this function gets called only once, whereas __baum_welch_summarize gets called once per data point and requires a full forward/backward pass of the data. I would expect savings, if any, to be minimal, but I am open to looking into it again.

**Comment by jmschrei** [comment]
Is this issue resolved?
