### ISSUE TITLE
Manually edit probability values in BayesianNetwork instance

### ISSUE THREAD

**Issue by TeeRev** [jmschrei/pomegranate#540]
Is it possible to edit probability values manually in a BayesianNetwork instance?

This would be useful for doing inference over a very large network (for which the training time/memory is too large) by breaking it into smaller, d-separated sub-network instances, each trained on their own datasets using _BayesianNetwork.from_samples()_, and where probabilities found using _predict_proba({})_ are passed between subnetworks by editing the values accordingly at the nodes situated on the network boundaries.

**Comment by jmschrei** [comment]
Are you talking about programmatically, or about by hand? you should be able to write the Bayesian network out to a JSON and edit it however you want, but that's not really programmatic. You could deal with the JSON programmatically if you'd like. I'd be wary about trying to edit values in the probability tables themselves because there is a Python level and a Cython level, and changes to the Python level aren't pushed to the Cython level. It might be better to create new table objects that have the values you want, stick them in to the network, and re-bake the whole thing.

**Comment by TeeRev** [comment]
Thanks very much for the speedy response.

Sorry, yes, I meant programmatically. Specifically, I was wondering if the BayesianNetwork class has its own method for making such modifications?

I agree that it fairly straightforward conceptually to save a sub-network to .json and then create new DiscreteDistribution / ConditionalProbabilityTable objects explicitly for an adjacent sub-network, though I'm slightly anxious about finding a fail-safe and clean way to parse the .json file and automate this process. 

I want to use _from_samples()_ on all nodes in a sub-network, then programmatically edit *some* of those nodes. To keep track of these nodes, node naming/indexing might make the process more robust. This perhaps adds weight to the previous suggestion that names are explicitly included in the return value of _predict_proba()_ as suggested in issue #527

**Comment by jmschrei** [comment]
Sorry for the late reply.

Unfortunately, there isn't anything built in that would allow you to modify these things easily. 

The nodes in the network should be in the same order that the data is presented in `from_samples()`. If you want to test this, you could modify all values in each column to be something like "0a", "0b", and "0c", where a/b/c refer to the columns. This will ensure that you're making the correct predictions for each column if you're worried. It shouldn't slow down the network, because it converts all keys to integers anyway.

I'll think about if there are better ways of adding in manual editing of networks, but I can't guarantee I'll add in anything to help. If you come up with something, let me know!
