### ISSUE TITLE
batch_size and batches_per_epoch in HMM model

### ISSUE THREAD

**Issue by j316chuck** [jmschrei/pomegranate#566]
I've been trying to run the hmm_tied_states.ipynb example with an additional batch_size and batches_per_epoch argument when I fit the model. This is so that I can run my large datasets with a smaller amount of data per epoch than the entire training set. When I run the vanilla fit argument without the batch_size and epoch arguments as shown in the original example... everything works as expected
![Screen Shot 2019-03-13 at 2 41 10 PM](https://user-images.githubusercontent.com/13524881/54316662-86c94f00-459e-11e9-86a3-c0a3a5afbe26.png)

However, when I run the fit command with batch_size and batches_per_epoch set both to 1, I get this ValueError. It seems as if the keymap does not recognize the symbol '3' which is weird because I am only using 'A', 'C', 'T', 'G' as symbols. The stranger thing is that batch_size works by itself and only if you set batches_per_epoch does this error occur? Could you let me know what I am doing wrong? 
![Screen Shot 2019-03-13 at 2 38 16 PM](https://user-images.githubusercontent.com/13524881/54316418-e96e1b00-459d-11e9-8583-e4e1bee2657e.png)

**Comment by jmschrei** [comment]
That's weird. I'm guessing this has to do with the internal conversion of non-integer symbols to integers through a keymap when using a discrete distribution.

Is your goal to have multiple `epochs` (EM update steps) per pass over your data, or just to be able to do an EM update step but you have too much data to fit in memory at once? You don't want to set `batches_per_epoch` to 1 if you're just trying to pass over the entire data set in an out-of-core manner.

I'll try to look into that example soon.

**Comment by j316chuck** [comment]
I want to have multiple epochs and a batch size > 1 preferably. I just set multiple epochs to a small number like 1 for this example but any input for batches_per_epoch will cause the ValueError

**Comment by jmschrei** [comment]
I'm guessing that there's an issue when the symbol doesn't occur in the minibatch. If I were you, I'd try implementing what you want by hand using the `summarize` and `from_summaries` methods. For example, let's say you have some X that has 1000 sequences in it that you'd like to train. You can train in a minibatch manner in the following way:

```python
batch_size = 50

for i in range(X.shape[0] // batch_size + X.shape[0] % batch_size):
    model.summarize(X[i*batch_size:(i+1)*batch_size])

model.from_summaries()
```

You'll need to implement your own stopping criterion, which can be done based on convergence because `model.summarize` will return the log probability of the data *before training on it*. When you've determined the model has converged, just do `model.clear_summaries()` instead of updating.

If you want to update before seeing the entire data set, but after a certain number of batches, you can modify the above code in the following manner:

```python
batch_size = 50
batches_per_epoch = 5

for i in range(X.shape[0] // batch_size + X.shape[0] % batch_size):
    if i % batches_per_epoch == 0:
        model.from_summaries()

    model.summarize(X[i*batch_size:(i+1)*batch_size])

model.from_summaries()
```

Sorry about the inconvenience.

**Comment by j316chuck** [comment]
Thanks for the response! I’ll do that!

—Chuck
