### ISSUE TITLE
No model is trained when using GeneralMixtureModel

### ISSUE THREAD

**Issue by zurkin1** [jmschrei/pomegranate#581]
When running the below code I get the below warnings and no real model is created (weights are -+infinity for example).

    import numpy as np
    import pandas as pd
    from pomegranate import *

    X=np.array([[2.44515009, 5.50218787, 2.78317919, 3.57474729, 2.28051024, 2.30735988, 3.14827695, 4.66004906, 2.17413335, 1.03239638, 4.49822428, 4.02841676, 1.57646796, 2.9348154 , 3.45762544, 1.86445921, 2.05579539, 1.01855821, 3.18763872, 1.58823228,        2.5070555 , 2.33347747, 1.79635148, 4.18190807, 3.79100177, 2.0217273 , 3.56959567, 1.74117038, 3.41538012, 5.36599237,  4.50731341, 2.28592422, 3.69336315, 2.47597859, 0.93218948, 1.91021177, 3.78694875, 2.30966696, 3.30454069, 3.73907217, 2.29007995, 1.49829356, 2.8240885 , 2.22911464, 2.8449105 , 2.83521877, 2.57443547, 1.86617824, 2.98622416, 1.9268491 , 2.33751329, 2.96892834, 4.32908499, 2.5824886 , 2.29107388]])
    model = GeneralMixtureModel.from_samples(GammaDistribution, n_components=2, X=X)

p.py:24: RuntimeWarning: invalid value encountered in true_divide
p.py:24: RuntimeWarning: invalid value encountered in less
p.py:24: RuntimeWarning: invalid value encountered in subtract
p.py:24: RuntimeWarning: divide by zero encountered in log

**Comment by jmschrei** [comment]
The first issue is that you should reshape your data to be (55, 1) rather than (1, 55). Right now your model thinks that it's a single 55 dimensional example, rather than 55 single values. A second issue is that, even after fixing that, GammaDistribution seems to break. Your best bet is likely to use a custom gamma distribution that fixes my stupid errors.
