### ISSUE TITLE
Slow BNSL with missing data

### ISSUE THREAD

**Issue by Wesserg** [jmschrei/pomegranate#589]
Hi. We are observing extreme slow down when running BNSL with missing variables (7days and still running). For the same dataset with imputed values the BNSL finishes within few hours. In both cases we are using 'exact' algorithm.

I was wondering if this is expected or is it a bug? Readthedocs mentions that the slowdown might occur in case of models based on multivariate normal distributions, not necessarily for Bayes nets. 

Could the issue be related to: [https://github.com/jmschrei/pomegranate/pull/571](https://github.com/jmschrei/pomegranate/pull/571) [We would appreciate a merge/pull if possible]

**Comment by jmschrei** [comment]
I can't think of a reason why you would get a slowdown when running BNSL with missing variables. The only difference is that, when getting frequencies for each entry, you ignore those with missing values. Can you post a minimally reproducing example?

**Comment by alexhenrie** [comment]
Here is a simple program that demonstrates the problem:

```
import numpy as np
from neurtu import delayed, Benchmark
from pomegranate import BayesianNetwork
from random import random

X = np.round(np.random.rand(10000, 15))
train = delayed(BayesianNetwork)().from_samples(X)

print('Without missing values:')
print(Benchmark(wall_time=True, cpu_time=True, repeat=3)(train))
print()

for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        if random() <= 0.1:
            X[i][j] = np.nan

print('With missing values:')
print(Benchmark(wall_time=True, cpu_time=True, repeat=3)(train))
print()
```

With the current Pomegranate code, training a Bayes net with 10% of the values missing is nearly twice as slow as training a Bayes net without missing values:

```
Without missing values:
6it [00:23,  4.16s/it]
      cpu_time  wall_time
mean  4.655360   4.824831
max   4.715996   4.914933
std   0.054074   0.092098

With missing values:
6it [00:43,  7.60s/it]
      cpu_time  wall_time
mean  8.568754   8.596677
max   8.596781   8.667951
std   0.035506   0.090385
```

With the improvements I proposed in #571, the performance gap narrows slightly but is still almost as bad:

```
Without missing values:
6it [00:23,  4.19s/it]
      cpu_time  wall_time
mean  4.708834   4.766239
max   4.733736   4.840934
std   0.039952   0.093201

With missing values:
6it [00:42,  7.45s/it]
      cpu_time  wall_time
mean  8.439062   8.471104
max   8.558999   8.552451
std   0.105226   0.099528
```

**Comment by jmschrei** [comment]
I am able to reproduce a slowdown, even after incorporating the changes. It looks like this might be related to the `reduce_dataset` parameter in `BayesianNetwork.from_samples`. This parameter will merge rows that have the same values and correspondingly increase the weight. When a data set has many repeated rows this can lead to a dramatic increase in speed because fewer overall calculations need to be performed. Essentially, the higher the covariance between examples, the larger the speedup using this track. However, when `nans` are randomly added to the data set this can decrease the number of repeated rows, and thus slow down the learning process.

For example: With `reduce_dataset=True`.

```
Without missing values:
       cpu_time  wall_time                                                                            
mean  20.021099  20.052867
max   20.075827  20.217315
std    0.080860   0.147105

With missing values:
       cpu_time  wall_time                                                                            
mean  25.076501  24.838830
max   25.298554  24.940744
std    0.285998   0.121369
```

and with `reduce_dataset=False`

```
Without missing values:
       cpu_time  wall_time                                                                            
mean  22.797783  22.819560
max   22.898038  23.066777
std    0.088831   0.219160

With missing values:
       cpu_time  wall_time                                                                            
mean  24.550130  24.505997
max   24.690316  24.600463
std    0.135456   0.088666
```

Can you see what effect this might have on your data set?

**Comment by alexhenrie** [comment]
Whoa! With `reduce_dataset=True`, it takes 30 hours to train a Bayes net on our data. With `reduce_dataset=False`, the time drops to 17 hours. Maybe we can improve on this further, but just knowing that we can safely turn off dataset reduction is a huge improvement, thank you!

**Comment by jmschrei** [comment]
That's really weird. It should be the opposite. Working with a reduced data set should always be faster or an equivalent amount of time as working with the full data set, as the reduced data set will, by definition, be smaller or an equal size. However, it's possible that the construction of the reduced data set is taking a significant amount of time, perhaps because you don't have the memory to store two copies of the same data set in memory and so the machine is using virtual memory?

Regardless, I'm glad that it's helping!
