### ISSUE TITLE
Why is the batch_size parameter not present for training bayesian networks from structure?

### ISSUE THREAD

**Issue by killerB97** [jmschrei/pomegranate#603]

**Comment by jmschrei** [comment]
The `summarize` function is present for Bayesian networks and you should be able to run it repeatedly on batches of data before calling `from_summaries` to update the parameters. It isn't added to `from_samples` because exact structure learning is difficult to do in a batch setting. In principle, it could be added to the `from_structure` method but I haven't done such. However, since `from_structure` involves only building the network object followed by a call to `fit`, you could run `from_structure` on a small subset of your data and then repeatedly call `summarize` on batches of your data afterwards.

**Comment by killerB97** [comment]
Hey, Thanks a lot for the prompt reply. This makes sense, will go ahead and follow what you mentioned here

**Comment by killerB97** [comment]
Another small query though, suppose I call summarize on batches of data after the initial from_structure call and a certain value of an (attribute/feature) has not been encountered before, it seems to be giving a key error. Is there any way around this?

**Comment by jmschrei** [comment]
You should either select examples for your initial batch that include all keys, or make a hand-crafted fake batch that does. Keep in mind that fitting a Bayesian network to new data is independent of the current parameters of the network, so using a fake batch won't effect training. Conceptually, it would be easy to add in a set of keys for each column as a parameter like sklearn does with `partial_fit`, but I just haven't done it.

**Comment by jmschrei** [comment]
Let's keep this convo to the new thread.
