### ISSUE TITLE
Training improvement = -inf

### ISSUE THREAD

**Issue by gioschibo** [jmschrei/pomegranate#660]
Hi! What does it mean when the following report is printed:

> [1] Improvement: -inf	Time (s): 43.02

> Total Training Improvement: -inf

> Total Training Time (s): 92.4355

I do not understand the -inf.  I am training a HMM with a mixture model of multivariate gaussians using 'labeled' option.
Thanks in advance.

**Comment by jmschrei** [comment]
Generally speaking, getting an improvement of -inf means that something went wrong with the training procedure. Most likely this is because a sequence of states for one of more of the sequences you're training on is not actually possible and so the probability of that sequence is -inf. Potentially, it's due to a bug in pomegranate. I'd go through your labels and make sure there isn't an issue somewhere.
