### ISSUE TITLE
[BUG] HMM Training sometimes stuck

### ISSUE THREAD

**Issue by IdioGuarino** [jmschrei/pomegranate#686]
Hi, I'm trying to train an HMM from my data. My data is organized in sequences of observations with different length, where each observation consist in a couple of value like:

data=[[[30,1000.6],[150,536.3],...,[1448,2188.7]],
      [[25,980.1],[220,827.9],...,[1280,3741.5]]]
        
this is my code:

```
dists=[pome.distributions.GammaDistribution, pome.distributions.GammaDistribution]
for n_states in nstate_list:
 print('Training of HMM with %s States' %n_states)
 mod,history=pome.hmm.HiddenMarkovModel.from_samples(distribution=dists,n_components=n_states, X=obs, name=pippo,verbose=True,return_history=True, n_init=3, random_state=0)
```

During the training, sometimes, after a certain number of complete iterations, the training becomes very very slow and and is unable to continue.
This is an example output:

```
Training of HMM with 5 States
[1] Improvement: 5291045.53869874       Time (s): 19.52
[2] Improvement: 3248445.809806794      Time (s): 19.14
[3] Improvement: 7528462.851135243      Time (s): 18.84
[4] Improvement: 8519733.17285239       Time (s): 18.77
[5] Improvement: 13443637.617080323     Time (s): 18.49
STUCK
```

Since this problem does not always occur, what could be the cause?

**Comment by jmschrei** [comment]
Currently, gamma distributions require their own internal optimization loop in order to fit parameters, in contrast to other distributions that can be easily fit using MLE (see https://github.com/jmschrei/pomegranate/blob/master/pomegranate/distributions/GammaDistribution.pyx#L192) I'm guessing that optimization is not converging quickly. Potentially, you're seeing that one state is getting all of the observations while the other is getting very few? It might be helpful if you could take a look at the number of observations assigned to each state during training. Unfortunately, the simplest remedy to this problem might be for you to implement your own custom distribution that's similar to my implementation of gamma distributions, except faster.

**Comment by IdioGuarino** [comment]
Thanks,
how do I see the number of observations assigned to each state during training?
Also, if I try to use a different distribution, I get the following errors:
- if I use a MultivariateGaussianDistribution, I get a segmentation fault
- if I use NormalDistribution the improvement is Nan

**Comment by jmschrei** [comment]
It sounds like there's an issue with the format of your data. It's difficult for me to diagnose without seeing your code or the data.

**Comment by IdioGuarino** [comment]
You have got the problem. Now my problem is: 
I have several time series so I need to fit my model in a cumulative way. If I apply the fit() method to the same model, iteratively on each time series, does the parameters of the HMM update cumulatively?

**Comment by jmschrei** [comment]
Each time you call `fit` you are performing EM. If you call `fit` multiple times, the initial parameters will be the output parameters from the previous round of EM. In that sense it is cumulative. If you only pass in new data in each round the model will not remember the sufficient statistics from the previous round because they would be different given the new data. If this is an issue you can always fit on the concatenation of data up until the current time point.

**Comment by IdioGuarino** [comment]
Thanks. Now, I have multiple training sequences with different length, where each observation consists of 2 variables. if I pass a list of sequences to method from_samples, where each sequence is a numpy array with shape ( Seq. Length,2), how is the training performed? Is training done as reported in the first answer to this question?

> So, if you have multiple training sequences, on the estimate step you should run each sequence so that it's initial observation vector aligns with the initial state. That way, the statistics on that initial state are collected from the first observations over all your observation sequences, and in general observation vectors are aligned to the most likely states throughout each sequence. You would only do the maximize step (and future iterations) after all sequences have been provided for training. On next iteration, you'd do exactly same thing.

https://stats.stackexchange.com/questions/95144/training-a-hidden-markov-model-multiple-training-instances

**Comment by jmschrei** [comment]
Yes, successive calls to `fit` would be equivalent to that solution.
