### ISSUE TITLE
Bayesian Network weights for samples

### ISSUE THREAD

**Issue by ingjpal** [jmschrei/pomegranate#692]
Hello,

I'm using the weights option to learn the Bayesian Network from the data structure. I can see by playing with values that I can improve my predictions with this weights over the samples. However I really don't understand what are these samples affecting inside the model. Can you please briefly explain me the procedure inside tyro code and recommend me some literature to read about it ? I see that you point this in your paper for "Finding the optimal Bayesian Network Given a Constraint Graph" as a good way to extend the constraint graphs method but I cannot find any references to this. Is this the same as Likelihood weighing ? See video : 

https://www.youtube.com/watch?v=GYcIruSqT_k 

Thank in advance for your help. 

Juan

**Comment by jmschrei** [comment]
Learning the structure of a Bayesian network is based on counting the number of times certain variable combinations happen. For example, if you have some number of variables, and x0 is always 0 when x1 is 1 and always 1 when x1 is 0, you'd put an edge between the two. When you pass in weights, you are counting the sum of the weights across all examples, rather than the sum of the count of examples.

**Comment by ingjpal** [comment]
Can you please suggest some references that show this ? 

Thanks

**Comment by jmschrei** [comment]
I don't know any papers that explicitly discuss this because it is just a simple extension of the normal score used to learn Bayesian networks. See p17 of this thesis https://www.cs.cmu.edu/~dmarg/Papers/PhD-Thesis-Margaritis.pdf except replace N not with the number of sample in the bin but with the sum of the weights of the samples.

**Comment by ingjpal** [comment]
Thank you very much for the fast reply.
