### ISSUE TITLE
[BUG] HiddenMarkovModel.from_samples incorrect distributions

### ISSUE THREAD

**Issue by NathanDeMaria** [jmschrei/pomegranate#695]
**Describe the bug**

When using labeled data in `HiddenMarkovModel.from_samples`, the distributions on the model that is returned don't make sense. It seems like there's some kind of off-by-one when assigning observations to distributions by label.

**To Reproduce**

```python
from pomegranate import HiddenMarkovModel, NormalDistribution

hmm = HiddenMarkovModel.from_samples(
    NormalDistribution,
    n_components=4,
    X=[[1, 11, 21, 31], [2, 12, 22, 32], [3, 13, 23, 33]],
    labels=[['a', 'b', 'c', 'd'],['a', 'b', 'c', 'd'],['a', 'b', 'c', 'd']],
    algorithm='labeled',
    state_names=['a', 'b', 'c', 'd'],
)

for s in hmm.states:
    if s.distribution:
        print(s.name, s.distribution.parameters[0])
```

Output
```
a 2.0
b 2.0
c 12.0
d 22.0
```

Where I'd expect

```
a 2.0
b 12.0
c 22.0
d 32.0
```

**Debugging**
I've tried running the `.pyx` code inside `.from_samples` directly in a Python REPL and it seems to be splitting the observations correctly, both on 0.12.0 and 0.11.2. But when running the `pip install`'ed wheel, I see this error.

**Comment by jmschrei** [comment]
Howdy.

Sorry about the confusion. Due to the way that models are constructed in pomegranate you need to explicitly pass in a start state token at the beginning of your labels. This is because all models have a hidden start state that the model begins in.  The start token takes the form {name}-start, where you can pass in name.  The following code should give you the correct answer. 

```python
hmm = HiddenMarkovModel.from_samples(
    NormalDistribution,
    n_components=4,
    X=[[1, 11, 21, 31], [2, 12, 22, 32], [3, 13, 23, 33]],
    labels=[['model-start', 'a', 'b', 'c', 'd'],['model-start', 'a', 'b', 'c', 'd'],['model-start', 'a', 'b', 'c', 'd']],
    algorithm='labeled',
    name='model',
    state_names=['a', 'b', 'c', 'd'],
)

for s in hmm.states:
   if s.distribution:
      print(s.name, s.distribution.parameters[0])
```

I'll update the documentation to make this more clear.
