### ISSUE TITLE
[BUG] Unable to use JointProbabilityTable in NaiveBayes

### ISSUE THREAD

**Issue by nikzasel** [jmschrei/pomegranate#696]
I want to predict probability of multivariate categorical, that is specified with JointProbabilityTable,  using NaiveBayes. But I keep getting this ValueError. 

Creating a multivariate variable
```
mgd1 = MultivariateGaussianDistribution(means=[1.0, 1.0], covariance=[[0.25,0],[0,0.25]])
mgd2 = MultivariateGaussianDistribution(means=[-1.0, -1.0], covariance=[[0.25,0],[0,0.25]])
```

Making a multivariate "categorical" variable
The meaning of these categories is that every entry which category is specified by positive number is a member of jpt1 and vice versa. It is required that different populations have different set of category values.
```
jpt1 = JointProbabilityTable.from_samples(np.round(mgd1.sample(100), 0))
jpt2 = JointProbabilityTable.from_samples(np.round(mgd2.sample(100), 0))
```

Running 
`NaiveBayes([jpt1, jpt2]).predict_proba([[-1,-1]])`

Will produce this error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
 in 
----> 1 NaiveBayes([jpt1, jpt2]).predict_proba([[-1,-1]])
pomegranate\bayes.pyx in pomegranate.bayes.BayesModel.predict_proba()
pomegranate\bayes.pyx in pomegranate.bayes.BayesModel.predict_log_proba()
ValueError: sample only has 2 dimensions but should have 1 dimensions
```

Enviroment:
pomegranate-0.12.0
Windows 10 x64

The reason why i want to do this is that I have multiple Discrete distributions, and they do have correlation. Using IndependentComponentsDistribution seems to neglect it. Maybe there is different way to model them using your library?

Thank you.

**Comment by jmschrei** [comment]
The way you wanted to use them was correct. There were a few issues. First, on my side, JointProbabilityTable objects were not recording their dimensions correctly, causing the error you saw. Then, they were not allowing doing vectorized log probability calculations. Both of these issues have been fixed in the latest patch (will be available in 0.12.1 soon).

However, there is a problem in the code you sent me. With only 100 samples there is a high probability that one (or both) of those distributions do not see the key (-1, -1). This causes a problem. If I changed the covariances to a diagonal of 0.1 and drew 10,000 samples the code worked.
