### ISSUE TITLE
Performance and accuracy of Baum-Welch for a discrete HMM

### ISSUE THREAD

**Issue by ikizhvatov** [jmschrei/pomegranate#698]
I have been considering pomegranate as a state-of-the-art replacement for outdated ghmm package (http://ghmm.sourceforge.net) for discrete HMM functionality. The application is about fitting a HMM on relatively short amino acid sequences and using the fitted model for classification, as in a recently published tool (https://github.com/artyomovlab/hmmhc).

In a quick comparison I found that pomegranate is significantly slower in Baum-Welch fitting. Even on multiple cores vs single-threaded ghmm, in my test the wall time is 30 minutes for pomegranate vs 3 minutes for ghmm. Moreover, the model fitted with pomegranate (from the same initial state, and with the same termination criteria) has distinctly lower classification performance than the one fitted with ghmm (AUC 0.82 vs 0.94). The details of the comparison can be seen and should be fully reproducible from https://github.com/ikizhvatov/pomegranate-vs-ghmm.

My question: is there anything that could be done to improve pomegranate performance in this setting?

**Comment by jmschrei** [comment]
Howdy.

Sorry you're encountering difficulties. There shouldn't be a big difference in accuracy (or really, speed) between the two because the algorithm is deterministic given the same initial conditions. Can you try setting the two to have the exact same initial transition matrix and emissions and time each epoch? I have a hunch that GHMM might be terminating faster than pomegranate, and because the time it takes is heavily dependent on the number of iterations, GHMM ends faster. It's possible that we have different semantics for what the stop threshold means--- 0.0001 is very very low for pomegranate. There are also times when using additional jobs can slow down training when each parallelizable chunk is very small. Try running it with only a single job?

**Comment by jmschrei** [comment]
I'm also not sure you're calculating accuracy in the best manner. It seems like you're training on a bunch of positive sequences and then classifying positive vs negative based on the log probabilities, but also dividing this number by the length of the sequence. I'm not sure this division is a good thing to do if you're using the metric directly for classification. I think an alternate approach is to have a HMM with two distinct paths from the start state to the end state---one modeling the positive sequences, and one modeling the negative sequences. You can then use the forward-backward algorithm to classify whether new sequences went down the path of the positive sequences or down the path of the negative sequences.
