### ISSUE TITLE
Deep Hidden Markov Model

### ISSUE THREAD

**Issue by mabuodeh** [jmschrei/pomegranate#720]
Hey Jacob,

I've gone over the deep hidden markov model code, and I wanted to know if it is based on Structured Inference Networks for Nonlinear State Space Models:
https://www.aaai.org/ocs/index.php/AAAI/AAAI17/paper/viewFile/14215/14380

In the paper, they replace both the observation and transition matrices with multi-layer perceptrons, and I'm not sure whether or not that was what you were going for when you added the neural networks to the hmm.

Thanks in advance!

**Comment by jmschrei** [comment]
Howdy

The implementation of deep HMMs in pomegranate is not based off that but it seems to be related. While there is neural network that maps observations to hidden states, there is only a normal transition matrix. The idea is essentially that, instead of using a set of probability distributions to map observations to hidden state (by calculating log probabilities and then softmaxing) you use a neural network to do the same predictive task---mapping observations to hidden states.

**Comment by mabuodeh** [comment]
Got it, thanks again
