### ISSUE TITLE
Is there anyway to update the transition matrix per sample?

### ISSUE THREAD

**Issue by TamimAhmEd177** [jmschrei/pomegranate#739]
I am trying to train an HMM in a supervised manner. I need to update the transition matrix manually per sample. I have seen the previous comments where the transition matrix is updated per observation.
Say, I have a feature set, x of size (n,m) where n is the sequence size, and m is the feature number.
I want to update the transition matrix manually for each sample in n. More precisely, I want to change how the model updates the transition matrix and incorporate dwell time-based updates for each sample. Is there any way to pass the transition matrix per sample?

**Comment by jmschrei** [comment]
I think what you're asking for is called a non-stationary transition matrix. Unfortunately, there currently isn't way to do that in pomegranate. If you know the number of steps in your sequence and the parameters of the matrix you could try do something like take the model on the left side and unroll it like on the right side, with different transition probabilities at each layer.

![image](https://user-images.githubusercontent.com/3916816/80562331-455f5300-899c-11ea-8aff-759771ff1138.png)

**Comment by TamimAhmEd177** [comment]
Thanks for the quick response. Yeah, I am trying to implement a dynamic state transition. The sequence steps are fixed and also, the values of the transition probabilities can be calculated for each sample in the sequence. Can you elaborate on the term 'unroll' in your comment?

**Comment by ghammad** [comment]
Hi all, 

is there any follow-up on that issue? Knowing how to implement a time-dependent transition matrix would be indeed really nice.
Thank you.

**Comment by jmschrei** [comment]
Unfortunately there have no new additions to pomegranate related to this. My only suggestion is the poorly drawn schematic above, where you have one copy of the nodes per time step and, rather than having transitions between nodes at the same time, you only have transitions between nodes at adjacent time steps (e.g. a->b becomes a_0 -> b_1 where a_0 is a at time 0 and b_1 is b at time 1).

> Thanks for the quick response. Yeah, I am trying to implement a dynamic state transition. The sequence steps are fixed and also, the values of the transition probabilities can be calculated for each sample in the sequence. Can you elaborate on the term 'unroll' in your comment?

When I say unroll I mean what I described above. If you have a set of states X you make one copy of the states per time step and you can change the transitions between time steps however you'd like. A problem with this approach is that you need to know the number of time steps (or the max number of time steps) in advance.

**Comment by cruyffturn** [comment]
Will the unrolled model be slower @jmschrei ? Assume the following hypothetical case where we define the same constant transition HMM with unrolling and without unrolling. Will there be a difference in how long it takes to train or do inference between the two?

**Comment by jmschrei** [comment]
An unrolled model will take longer to train because the algorithms (both training and inference) take time proportional the number of edges in the model. An unrolled model will have the number of edges in the rolled model multiplied by the number of timepoints. The reason that the rolled model is faster is because it doesn't have to be concerned about what time point the example is in one of the states, whereas the unrolled model does.
