### ISSUE TITLE
[QUESTION] GMM with Poisson Distributions weights component as 0

### ISSUE THREAD

**Issue by jaymoore-research** [jmschrei/pomegranate#756]
I am training a GMM with Poisson Distributions for discrete biological data, where the model is initiated `from_samples`. The results of the one of the components are always `0` when testing using the `predict_proba` GMM method. This is regardless of the number of components the model was initialized with. 

In these cases, the weight of the component in the model is always `0`, leading to results that are `0`, which makes sense to me. Why is that component `0` if it was trained on the same data it is being tested on? 

The training data is predominantly `0`s and discrete values going up to around `10`. The Poisson lambda parameter equal to `0` for the model. I am not sure of the connection of what could be causing this, but I would prefer for this first component to have a fitted weight since a lot of the data is `0`.

I would also like to add that this behaviour disappears if I add `+1` to the array below, but I'm still confused by the current results. Here is a reproducible example using v0.12.2 on Python 2.7.17:

```
import pomegranate
import numpy as np

valueArray = np.array([0., 1., 1., 0., 1., 1., 0., 0., 2., 0., 1., 2., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 3., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 2., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

valueArray2 = valueArray.reshape( ( len( valueArray ), 1 ) )

model = pomegranate.GeneralMixtureModel.from_samples(  pomegranate.PoissonDistribution, 3, valueArray2, init='kmeans++' )

result = model.predict_proba( valueArray2 )

print model

print result[0:10]
```

Here is an example output:
```
{
    "weights" : [
        0.0,
        0.09033289118196673,
        0.9096671088180334
    ],
    "distributions" : [
        {
            "frozen" : false,
            "class" : "Distribution",
            "parameters" : [
                0.0
            ],
            "name" : "PoissonDistribution"
        },
        {
            "frozen" : false,
            "class" : "Distribution",
            "parameters" : [
                0.7110762812211925
            ],
            "name" : "PoissonDistribution"
        },
        {
            "frozen" : false,
            "class" : "Distribution",
            "parameters" : [
                0.29215789060647573
            ],
            "name" : "PoissonDistribution"
        }
    ],
    "class" : "GeneralMixtureModel"
}

[[0.        0.0613127 0.9386873]
 [0.        0.1371684 0.8628316]
 [0.        0.1371684 0.8628316]
 [0.        0.0613127 0.9386873]
 [0.        0.1371684 0.8628316]
 [0.        0.1371684 0.8628316]
 [0.        0.0613127 0.9386873]
 [0.        0.0613127 0.9386873]
 [0.        0.2789804 0.7210196]
 [0.        0.0613127 0.9386873]]
```

**Comment by jmschrei** [comment]
The expectation-maximization process (or the initial K-means clustering) can sometimes lead to components that have no examples. However, in this case, it looks like the reason is the prevalence of 0's. Essentially, you're correct that there is a component that is trying to fit exclusively to the 0's. This happens because you can get a big probability boost in having a component solely model 0s when you have integer based data and a big chunk of the data is 0. However, because lambda must be positive but is estimated to be 0 when fit to 0's, the component returns NEGINF when calculating the log of lambda and so no future examples can be assigned to it.

There are three solutions you can take. The first is to add a small constant to your entire data set (such as 0.01) so that you don't have any true zeros. The second is that you can remove all 0s when fitting the model. This may cause an inflation of your lambda values though.  The third is implement your own Poisson distribution as a custom distribution that is regularized to not fit exclusely to 0's. I'm not sure precisely what regularization would be best though.
