### ISSUE TITLE
[BUG] Python crashes with SIGABRT when using silent states

### ISSUE THREAD

**Issue by YuriOsokin** [jmschrei/pomegranate#801]
**Describe the bug**
The model with 6 states crashes python with a SIGABRT signal. The model does not contain any loops of silent states.
Running with python3.8.3
pomegranate==0.13.3
MacOS Catalina 10.15.5

**To Reproduce**
The attached code reproduces the bug.
[pom_bug.txt](https://github.com/jmschrei/pomegranate/files/4965843/pom_bug.txt)

**Comment by jmschrei** [comment]
Sorry for the delay. I was able to reproduce the error. Weirdly enough the code seems to run when the sequence length is 10 or fewer elements, but crash when hitting 11 or more.  The problem seems to be something related to state_1. When I remove it from the code (but leave state_4 in) it seems to run fine. I think it might be related to having one silent state (model.start) go to another silent state with a probability of 1. Just use model.start as the silent state.
