### ISSUE TITLE
Clarification regarding missing data in BayesianNetwork.probability

### ISSUE THREAD

**Issue by ekosman** [jmschrei/pomegranate#804]
Hi,

I'm trying to predict the joint probability of a few observations which contain missing data. As I understand, this could be done by calling the `probability` method of `BayesianNetwork`. However, I encounter a behavior that does not match expectations. For example, When calling:

```python
model.probability([[np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 1, 1]])
```

It returns `1.0`, While calling:

```python
model.probability([[np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 1, 2]])
```

returns `1.0` too.

I probably do something wrong since the joint probabilities should sum to 1.

Is it the right way to calculate joint probabilities with promegranate?

**Comment by jmschrei** [comment]
Howdy

Sorry, I think you're misunderstanding the function. It requires that you have an entire observation to calculate the log probability. If you don't have the entire observation it defaults to 1. There have been some efforts to add in probability calculations with missing data but, because those involve marginalizing over a potentially exponential number of combinations, are difficult to implement correctly.
