### ISSUE TITLE
[Question] Creating "mask" for transition/emission matrix that fixes values in place

### ISSUE THREAD

**Issue by b2jia** [jmschrei/pomegranate#813]
Pomegranate is great! Thank you for your hard work.

Is there a way to fix (or to use a word in the documentation, "bake") certain transitions in place, while allowing other parameters in the transition matrix to be updated in Viterbi or Baum-Welch learning? 

For instance, I can imagine a mask that specifies which "connections" between states are forbidden. In which case, I would like to zero out certain values, and still make the remaining adjustable parameters satisfy the singularly stochastic requirement of the transition matrix (ie. row sums = 1).

**Comment by jmschrei** [comment]
Yes, you can freeze certain components. For each distribution, you can use the method `freeze` (https://github.com/jmschrei/pomegranate/blob/master/pomegranate/base.pyx#L93) on the distribution object to prevent those parameters from being updated. You can set certain edges to not get updated by assigning a very large pseudocount  when creating the model, (like 1e10) (https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L407) to each edge that you don't what to update, and then call the `fit` method with `use_pseudocount=True`.

**Comment by jmschrei** [comment]
In terms of preventing some edges from existing-- once you set the transition probability to 0 (either by not including the edge when adding edges manually with `add_transition` or by passing in a matrix to `from_matrix`) the transition probability will never go above 0. However, there isn't a mask you can pass into the `from_samples` method to prevent certain edges from existing. This is, in part, because you won't know which cluster will correspond to which points.
