### ISSUE TITLE
[Question] Bernoulli naive Bayes classifier

### ISSUE THREAD

**Issue by hylkedonker** [jmschrei/pomegranate#835]
Hi,

I would like to switch from sci-kit learn to Pomegranate for my NaiveBayes model. If my understanding is correct, sci-kit learn's `BernoulliNB` would be equivalent to `NaiveBayes.from_samples(BernoulliDistribution,..)`. However, I seem to get different results when comparing these two models. Here an example where I get `NaN` values from pomegranate when predicting an out-of-sample category (despite the `pseudocount=1`), but proper floats from the sci-kit learn counterpart:
 
```Python
from numpy import array
from pomegranate import *
from sklearn.naive_bayes import BernoulliNB

X_train = array([
    [1., 0., 1., 0., 1.],
    [1., 0., 1., 0., 1.],
    [1., 0., 1., 0., 1.],
])
y_train = array([0, 0, 1])
X_test = array([[1., 0., 1., 0., 0.]])

pmodel = NaiveBayes.from_samples(
    BernoulliDistribution, 
    X_train, 
    y_train,
    pseudocount=1.0,
)
p_pom = pmodel.predict_proba(X_test)
print(p_pom)
# prints: [[nan nan]]

skmodel = BernoulliNB(alpha=1.0).fit(X_train, y_train)
p_sk = skmodel.predict_proba(X_test)
print(p_sk)
# prints: [[0.70611659 0.29388341]]
```

Am I missing something obvious, or is this perhaps a bug?

My pomegranate version is `0.12.0`.

Thanks in advance,

Hylke

**Comment by jmschrei** [comment]
So, you getting a NaN is a problem because pomegranate should never return NaN's. However, conceptually, I'm not sure I understand why sklearn is returning what it does. Both components of the naive Bayes should have the same underlying distributions and so the likelihood of each class should be the same regardless of feature smoothing. However, the prior probability should favor class 0 because 66% of training examples have that class. If you smooth that by adding a pseudocount of 1 to each class, you should get that 60% of examples fall under class 0. 

Regardless, it's probably not great to compare the two on this edge case.  If you look at more random data you get basically the same answer.

```python
>>> X_train = numpy.random.randint(2, size=(50, 3))
>>> X_test = numpy.random.randint(2, size=(50, 3))
>>> y_train = numpy.random.randint(2, size=50)
>>> 
>>> NaiveBayes.from_samples(BernoulliDistribution, X_train, y_train, pseudocount=1.0).predict_proba(X_test[0:1])
array([[0.37728886, 0.62271114]])
>>> BernoulliNB(alpha=1.0).fit(X_train, y_train).predict_proba(X_test[0:1])
array([[0.37868463, 0.62131537]])
```

**Comment by hylkedonker** [comment]
Thanks for getting in touch. Indeed, for me too it is not directly obvious how the values arise from the sklearn estimator without peeking at the code. 
At any rate, I would say that this "edge case" is -- in the presence of pseudocounts -- a mathematically well posed inference query. Is there any way to work around this? My dataset is comprised of a large sparse matrix with not so many records, and when doing cross validation it may happen that a category drops out in one of the folds.

**Comment by jmschrei** [comment]
You might try adding one example per class for each of your folds with a corresponding weight of 0. That should make each class show up in each fold. If you get NaNs, maybe make the weight tiny but non-zero, like 1e-6.
