### ISSUE TITLE
[Question]  Question about from_structure in bayesian network

### ISSUE THREAD

**Issue by lwgkzl** [jmschrei/pomegranate#837]
When I use from_str to construct a Bayesian network,for example:
```model = BayesianNetwork.from_structure(X, structuretunple) ```
 if the input X contains miss_value, is the Bayesian model using the MLE or EM algorithm for parameter learning?
Thanks for any help！

**Comment by jmschrei** [comment]
Howdy

pomegranate by default uses MLE. You can manually implement EM in a fairly straightforward manner by running `from_samples`, then imputing the missing values, then running `from_samples` again and re-imputing the missing values until convergence. I never got around to adding it, even though it's convenient and fairly straightforward.

**Comment by lwgkzl** [comment]
> Howdy
> 
> pomegranate by default uses MLE. You can manually implement EM in a fairly straightforward manner by running `from_samples`, then imputing the missing values, then running `from_samples` again and re-imputing the missing values until convergence. I never got around to adding it, even though it's convenient and fairly straightforward.

Thank you very much ：）

**Comment by lwgkzl** [comment]
> Howdy
> 
> pomegranate by default uses MLE. You can manually implement EM in a fairly straightforward manner by running `from_samples`, then imputing the missing values, then running `from_samples` again and re-imputing the missing values until convergence. I never got around to adding it, even though it's convenient and fairly straightforward.

If I use the from_sample function, I get MemoryError, my Bayesian network structure is known and i uses the ```include_edge``` parameter, my Bayesian network contains 70 nodes in two layers, including four parent nodes, as shown below：
![image](https://user-images.githubusercontent.com/30727306/99370252-69fb2800-28f8-11eb-8933-710312f5e943.png)


There is another problem, in case I only have a tree of depth 2, i.e. a father and about 50 son nodes, find the edge probability of the parent node with the values of all children nodes observed. When I use the [predict_prob] function, it takes about 1s to give me the answer, and I wonder why it takes so long.

**Comment by jmschrei** [comment]
If you already know the structure of the network, and are just trying to learn the parameters of the tables, you should use the `from_structure` method instead of the `from_samples` method. With the `from_structure` method you pass in a known structure and the data and it returns a BayesianNetwork object with the table parameters derived from the data.

You might be encountering a memory error because the network you are specifying is too big. When doing structure search, each node takes O(k**n) memory, where k is the number of symbols that variable can be, and n is the maximum number of potential parents.

pomegranate uses an approximate message passing algorithm for inference. This is faster than the exact algorithm (in theory) but can still be slow for large networks.

**Comment by lwgkzl** [comment]
Thank you for your timely response OvO
