### ISSUE TITLE
[Question] Is it possible to achieve this using Pomegranate?

### ISSUE THREAD

**Issue by jeongsoolee09** [jmschrei/pomegranate#843]
Hello! I have been using Pomegranate to predict the marginal probability of each states in a Bayesian Network given some observation, using `predict_proba`. However, I have thought of a more complicated set of operations, given two Bayesian Networks. I am wondering if this can be achieved by the set of APIs provided by Pomegranate.

1. Given two Bayesian Networks `G1` and `G2`, first get the marginal probabilities of each node of `G1`, given some set of observations.
2. Freeze the above marginal probabilities of `G1` after the observation so that the marginals do not get affected by future runs of loopy belief propagation.
3. Merge `G1` and `G2` by adding some edges between the graphs.
4. Run a loopy belief propagation on the merged graph with an empty set of evidence. Now, `G2`'s marginal probabilities should be updated due to the algorithm, while `G1`'s marginals should stay intact since the states are 'frozen'.
5. Memorize `G2`'s marginals from the above (call the distributions as `D`), and cut off all edges connecting `G1` and `G2`.
6. Considering `D` as the initial marginals of `G2`, run several loopy belief propagations as observations get accumulated.

I notices distributions for BNs, namely `ConditionalProbabilityTable` and `DiscreteDistribution` has the ability to be 'frozen', but the states based on them have no attribute called `frozen`. Therefore, I have tentatively concluded that my plan cannot step any further than operation 2.

Is there any way I can run the above set of operations? I know it sounds esoteric, but I am very curious at the same time about the possibility.

**Comment by jmschrei** [comment]
Howdy

There isn't a way to do that automatically, but it can certainly be implemented with some code on your side. What I'd recommend you do is create two objects: B1, which is G1 and G2, and B2, which is just G1. I would start off by running loopy belief propagation on just B2. Then, I would extract the states and pass them in as evidence to B1. User-provided evidence can be symbols (hard) or probability distributions (DiscreteDistribution objects I think). Then, run loopy belief propagation on B1. The G1 nodes will be fixed because you provided them as evidence. 

I'm not sure I fully understood your steps 5/6, but I think that can also be done. You would create a new object, B3, which has the same structure as G2, but with initial probabilities set to the output probabilities from the B1 inference step above. Then, you'd run inference with no evidence on B3, and use those probabilities. 

Let me know if that helps.
