### ISSUE TITLE
Unexpected behavior from predict_proba with correlated data

### ISSUE THREAD

**Issue by ensbergj** [jmschrei/pomegranate#848]
Greetings,

I am using python 3.6.3 with pomegranate version 0.13.5 and I am getting unexpected behavior from the BayesianNetwork predict_proba method when using correlated data.  Specifically, I have a simple three-node BN with two parent nodes (A & B) and one child node (C).  The training data is such that the value of C is random, but will be 1 whenever A is 1 or B is 1.  I therefore expect that P(C=1|A=1) = 1 and P(C=1|B=1)=1.  When my training data is such that A and B are perfectly correlated, I do not get the expected answer.

The issue can be reproduced using the following code:

from pomegranate import *
import pandas as pd
import numpy as np

df = pd.DataFrame()
df['a'] = np.random.randint(0,2,1000)
df['b'] = df['a']
df['c'] = np.random.randint(0,2,1000)
df['c'].loc[(df['a'] == 1) | (df['b'] == 1)] = 1

print(df['c'].value_counts())
print(df['c'].loc[(df['a'] == 1)].value_counts())

model = BayesianNetwork.from_structure(df,structure=((),(),(0,1,)),state_names=['a','b','c'])
model.bake()

print(model.predict_proba({'a':1}))

Which outputs:
1    730
0    270
Name: c, dtype: int64
1    493
Name: c, dtype: int64
[1
 {
    "class" : "Distribution",
    "dtype" : "numpy.int32",
    "name" : "DiscreteDistribution",
    "parameters" : [
        {
            "0" : 0.507,
            "1" : 0.4930000000000001
        }
    ],
    "frozen" : false
}
 {
    "class" : "Distribution",
    "dtype" : "numpy.int32",
    "name" : "DiscreteDistribution",
    "parameters" : [
        {
            "0" : 0.25350000000000017,
            "1" : 0.7464999999999998
        }
    ],
    "frozen" : false
}]

Note that the probability of C=1 is 0.746... when it should be 1.  

It is also worth noting that the model gives the correct answer if the A and B are changed to be uncorrelated.  Specifically:
df = pd.DataFrame()
df['a'] = np.random.randint(0,2,1000)
df['b'] = np.random.randint(0,2,1000)
df['c'] = np.random.randint(0,2,1000)
df['c'].loc[(df['a'] == 1) | (df['b'] == 1)] = 1

print(df['c'].value_counts())
print(df['c'].loc[(df['a'] == 1)].value_counts())

model = BayesianNetwork.from_structure(df,structure=((),(),(0,1,)),state_names=['a','b','c'])
model.bake()

print(model.predict_proba({'a':1})) 

Which outputs:
1    759
0    241
Name: c, dtype: int64
1    525
Name: c, dtype: int64
[1
 {
    "class" : "Distribution",
    "dtype" : "int",
    "name" : "DiscreteDistribution",
    "parameters" : [
        {
            "0" : 0.0,
            "1" : 1.0
        }
    ],
    "frozen" : false
}
 {
    "class" : "Distribution",
    "dtype" : "numpy.int64",
    "name" : "DiscreteDistribution",
    "parameters" : [
        {
            "0" : 0.0,
            "1" : 1.0
        }
    ],
    "frozen" : false
}]

Apologies if I am missing something obvious and thank you in advance for your input!

**Comment by jmschrei** [comment]
Howdy

I think that the issue arises because you don't have any examples where A != B. The conditional probability table for C (`model.states[2].distribution`) thus default to 0.5 for both A=1,B=0 and A=0,B=1. Because pomegranate uses loopy belief propagation, which is an efficient but approximate inference algorithm, it doesn't know that you can only have A=1,B=1 or A=0,B=0, and so marginalizes over all possibilities (including A=0,B=1 and A=1,B=0 where P(C=0)=P(C=1)=0.5 because you have no data to fit meaningful probability distributions). Essentially, the model sees that A can be 1 or 0 half the time, B can be 1 or 0 half the time, and because there's no edge between them it doesn't know that these probabilities are connected.

Let me know if you have any other questions!

**Comment by ensbergj** [comment]
Thank you for the quick feedback!  

That this is the issue makes sense.  For future releases, it would be useful if pomegranate provided an option to get the exact conditional probabilities one would expect from counting the rows in the training data.  For example, would it make sense to use default probabilities of 0.0 (instead of 0.5) for A,B combinations that are not present in the training data?  Any thoughts on this?

**Comment by jmschrei** [comment]
pomegranate does compute the exact conditional probabilities. The issue is what is P(C=0|A=0,B=1) when there are no examples of A=0,B=1? In this case, pomegranate defaults to P(C=0|A=0,B=1) = 0.5 and P(C=1|A=0,B=1) = 0.5. If it set both of those to 0, that would no longer be a valid probability distribution.

**Comment by ensbergj** [comment]
Thanks for the helpful clarification.  

I think my confusion originated from how I expected impossible events to be handled in the absence of A and B being connected via edge.  Specifically, for:

P(C = 0 | (A,B) = impossible combination) = P(C=0, (A,B) = impossible combination)/P((A,B) = impossible combination) = 0/0 = undefined
P(C = 1 | (A,B) = impossible combination) = P(C=1, (A,B) = impossible combination)/P((A,B) = impossible combination) = 0/0 = undefined

Since these impossible combinations can never happen, the number of rows on our training dataframe satisfying these conditions is zero and it seems intuitive that the conditioned probabilities will also be equal to zero even though they are technically undefined.  

It may still be useful to provide the user with the ability to do something like:
1. explicitly tag input variable combinations that are not present in the training data as "impossible".
2. explicitly set the probabilities for variables (e.g., C) conditioned on "impossible" combinations to some user-specified value (e.g., 0.0, 1/Nc, etc.).

For now, I think we can accomplish what we need by manually constructing the conditional probability table (e.g., https://github.com/jmschrei/pomegranate/issues/849).  

Thanks,
Joseph

**Comment by jmschrei** [comment]
There should never be impossible undefined events in the format of a Bayesian network. What's happening in this example is that your network does not include all of the edges that it should. Specifically, there is a dependence between A and B that you are not telling your model about. Because you are not telling your model about this dependence, the inference step from the model does not include it. A more accurate model, in your case, would have an edge between A and B and specify, in the conditional probability table of the child, which combinations can happen.
