### ISSUE TITLE
Market basket analysis using bayesian networks in pomegranate

### ISSUE THREAD

**Issue by Raviteja973** [jmschrei/pomegranate#859]
I am trying to do market basket analysis using bayesian networks. I had around 15k rows and 170 columns(products).
Is it possible to create a bayesian model for this data and then predict using the model created?
Any suggestions on how to go about it?

**Comment by jmschrei** [comment]
I'm not sure what market basket analysis is, sorry. If you're trying to do clustering I would suggest using a mixture model or K-means clustering approach.

**Comment by Raviteja973** [comment]
Market Basket Analysis is used to uncover associations between items. It works by looking for combinations of items that occur together frequently in transactions. To put it another way, it allows retailers to identify relationships between the items that people buy. Association Rules(Association rule mining) are widely used to analyze retail basket or transaction data, and are intended to identify strong rules discovered in transaction data using measures of interestingness, based on the concept of strong rules.  
So basically i have list of list of transactions and need to create a bayesian model to find patterns in the data and the model should be able to predict the other frequently bought products given a set of products.
Data format:  [[milk, eggs, bread ,butter],[beer, soda, chips, milk],[butter, eggs, cookies]........]
i have dataset as above with around 15k transaction details and 170 unique products among those transactions.
Now i am interested to find patters in the dataset using bayesian model and thus predicting frequently bought items if a set of products is given.

**Comment by hayesall** [comment]
@Raviteja973 You're probably looking for something closer to "association rule mining" rather than "Bayesian Networks" specifically.

Weka has an implementation of the Apriori algorithm, which could be a good place to start looking (see [Weka Association Rule Mining](https://www.tutorialspoint.com/weka/weka_association.htm)).

If you are curious about Bayes nets and their relationship to rule learners, [Gopalakrishnan 2010](https://pubmed.ncbi.nlm.nih.gov/20080512/) contains an algorithm for converting Bayes nets to association rules. I implemented a version here: ([hayesall/bn-rule-extraction](https://github.com/hayesall/bn-rule-extraction)) but it's far from being production ready.

**Comment by jmschrei** [comment]
I think that there are a variety of methods that one could use for this. Bayesian networks could potentially be used (and used in conjunction with the tool from @hayesall), but I'm not sure that they're the best tool for the job. I'd recommend trying clustering on a matrix where the rows are items, the columns are transactions, and the data is binary (1 if purchased and 0 if not purchased). Each of the clusters from a clustering algorithm can be thought of as a "basket" because you sets of items that are purchased together. It will also be significantly faster.

**Comment by Raviteja973** [comment]
I had implemented with association rule mining algorithms  but we want to check whether bayesian networks(or any graph algo)might work even better for our case. so we are trying on this but getting memory issues. i am assuming as we have 170 unique items as columns is the issue as we need to create each item as a node and create edges based on transactions.
