### ISSUE TITLE
Inference: predict_proba - Time taking function call

### ISSUE THREAD

**Issue by prajwalainapur** [jmschrei/pomegranate#861]
Hi @jmschrei , I find your package for bayesian networks as one of the quickest as well as elegant for structure learning as well as parameter learning. But one minor issue i have faced during my implementations on my projects are to do with the inference. I am able to generate the structure as well as the CPD table for my training data within few seconds / minutes. But when validating the model over my test data, per se, i have 10000 samples in my test, it takes really long time to finish inference for all the samples. Training times is significantly lower in comparison to testing time. I am using predict_proba() method for inference. So basically i call the method for each of the test data point in a loop.
Is there any other elegant way of implementation for testing than this? If not, what could be potentially done to reduce the testing time.

**Comment by jmschrei** [comment]
Howdy. Thanks for the kind words.

Unfortunately, that function is slow because it uses loopy belief propagation. Because the set of symbols generally differs across nodes, it's difficult to make use of matrix multiplies or other obvious speedups. I've also run low on developer time, and so refactoring the prediction code to be faster hasn't been possible. I think the most reliable speedup is parallelizing the predictions. You can do this by passing in a number to the `n_jobs` parameter, or manually by loading up a copy of the model to each thread and making predictions in a manner you specify.

**Comment by prajwalainapur** [comment]
Thanks a lot for the answer! I'll send a pull request if i can refactor that particular function to perform more efficiently.

**Comment by prajwalainapur** [comment]
Thanks a lot for the answer! I'll send a pull request if i can refactor that particular function to perform more efficiently.
