### ISSUE TITLE
will it work for multivariate time series prediction 

### ISSUE THREAD

**Issue by Sandy4321** [jmschrei/pomegranate#862]
great code thanks
may you clarify : 
will it work for multivariate time series prediction   both regression and classification 
1 
  where all values are continues values 
    weight    height     age   target 
1   56        160    34    1.2
2   77        170    54    3.5
3   87        167     43   0.7
4   55        198    72    0.5
5   88        176     32   2.3

2
or  even will it work for multivariate time series where values are mixture of continues  and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

    color        weight     gender  height  age  target 
1    black       56             m   160    34    yes
2    white       77             f   170    54    no
3    yellow      87             m   167    43    yes
4    white       55             m   198    72    no
5   white       88              f   176    32    yes

**Comment by RoboTums** [comment]
Hey! 
It really depends on what you want to model/predict.

 The HiddenMarkovModel class looks like a good contender to do what you want to do. The way it could work in your case is that you can treat the HMM (hiddenMarkovModel) as a state observer model. 
Essentially, you have these obeservations (your data) and which get sampled from the state (the underlying distribution behind your data), and all of this is in the context of some time period t. So, for each time period, you have these two nodes, a state node and a observation node. As the observations are assumed to not be casually related (you said you were trying to do regression here, thats a fundamental assumption), you can create links from the state from time t-1 to time t. 

Your HMM will look something like this: 
![image](https://user-images.githubusercontent.com/29108771/104476337-21758900-558e-11eb-823e-84c94de0b44c.png)

Thing is, you have multiple classes of observations. Thats okay! You can make it multi-dimensional because all of this can be vectorized. 

Will it work for multivariate time series regressor/classifier?
-- Yes-- you just input the test data as a sequence, and your HMM that fit on your train data will return the probabilties of a specific target.  Just think about it as you would any model. 

Will it work for multivariate time series where values are mixture of continues and categorical values?
--Yes- but you need to be more careful. Just make sure that the way you model both the discrete and continous values is consistent across your implementation. 

If you'd like examples, check out this tutorial here:
https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_3_Hidden_Markov_Models.ipynb

And another:
https://nbviewer.ipython.org/github/jmschrei/yahmm/blob/master/examples/Global%20Sequence%20Alignment.ipynb

**Comment by Sandy4321** [comment]
great thanks
do you have example where your code outperforms deep NN?

**Comment by RoboTums** [comment]
on what criteria? HMMs are explainable-- DNNs arent. DNNs give better point estimates, HMMs give better posterior distributions. Gaussian Processes are also something to consider if your time isnt discretely valued/ you don't want the markov assumption. The best models for a lot of time series analysis use both HMMs and DNNs together. I suggest you learn some of the math behind both of these, as just looking for code/forking repos won't get you anywhere when you run into bugs or misconceptions.

**Comment by jmschrei** [comment]
1. Yes, you can implement multivariate HMMs in pomegranate. This can be done using MultivariateGaussianDistribution objects or IndependentComponentDistributions objects. The first will learn a Gaussian distribution with a full covariance matrix. The second allows you to specify different, independent, distributions for each feature. For example, one feature could be an exponential distribution and the next could be a normal distribution.
 
2. In theory, one should be able to have both categorical and continuous variables in the same HMM. In practice, I think that pomegranate does not work too well with that due to a quirk in how I implemented discrete values. Sorry about that. 

Thanks, @RoboTums, for answering some questions. However, I'd disagree that DNNs aren't interpretable. There is a huge body of work on principled ways of doing feature attributions given black-box models like DNNs. These explanations can be more useful than simple model inspection, which is possible for linear or probabilistic models.

I wouldn't say that DNNs are better than HMMs, or the other way around, but I would say that there are types of problems where I would expect HMMs to outperform DNNs. In cases where you have tons of labeled data, and the data is complex, I would expect DNNs to dramatically outperform HMMs.  In cases where you have a small amount of unlabeled data I would expect HMMs to outperform DNNs. Essentially, due to their inherit constraints (e.g. modeling a feature using a simple distribution rather than a complex non-linear function) HMMs work really well when the patterns are simple or when there is not that much data. Although DNNs can work on unlabeled problems I've found that, when the input data are sequences, HMMs do better than DNNs.
