### ISSUE TITLE
Interpretation of Multivariate HMM using Pomegranate

### ISSUE THREAD

**Issue by prescientlyd** [jmschrei/pomegranate#890]
Currently I am dealing with a project in which I use multiple sequences to predict two sequences. Just as an example, imagine I have historical data on temperature, humidity, wind speed, fire incidence and precipitation of national parks, and I want to predict whether there will be fire incidence and precipitation next day. I was wondering how can I find the importance of each sequence when predicting fire incidence and precipitation? For example, maybe temperature is more important than wind speed when it comes to predicting fire incidence. Or even better, is there a parametric way in which I can actually find parameters that can tell me the importance of these input sequences, and that higher temperature increases the chance of fire (positive parameter) and humidity decreases the chance of fire (negative parameter)?

Thank you!

**Comment by jmschrei** [comment]
I assume that your hidden states are each combination of your two labels? In that case, you can compare the probability distributions learned over the inputs. I'd need to know more about how exactly you're choosing to model this data before I can give specific advice, though. If you have the features and the labels it sounds more like a supervised prediction problem rather than one where an HMM would be best, though.

**Comment by prescientlyd** [comment]
Thanks jmschrei for your answer. I am not sure what do you mean by "combination of two labels" as I come from an econometrics back ground. Let me try to explain in more details what I try to do.

Take transition process as an example, where s(t) represents the latent state in period t. Here, I will assume that this transition process takes a logistic form: P(s(t)|s(t-1))=exp(b*x)/(1+exp(b*x)). Of course, the value of b will be different for different latent state s(t). So Ideally I want to find a way that I can actually estimate/obtain the value of b after I fit a HMM model. The emission process will also be parameterized in similar ways (for example, )

Again, my training is mainly from Econometrics, so please let me know if I did not explain something clearly.

**Comment by jmschrei** [comment]
Your two labels are fire incidence and precipitation. It sounds like you have each of these labels at each time step. The hidden states in HMMs don't correspond to labels as cleanly as in a supervised prediction problem. Rather, because you must be in one of the hidden states at each point in your time series, you should have one hidden state for each combination of label sets, i.e. the Cartesian product of labels across all variables.

You should be able to easily pull the learned distributions out of a trained model. But I'm still not sure that a HMM is actually the right model for your problem. It sounds like a supervised machine learning problem to me.

**Comment by yingdalu** [comment]
Thank you again for your comment. I guess you got confused because my example was not appropriate. The reason why I want to use a HMM is that my focus is on the latent state, specifically, how latent state transit, and how latent state influences output. 

Also, after digging through the document, I think viterbi function is the one I am looking for (i.e. generate the most likely path). I will play around with this code more.
