### ISSUE TITLE
[BUG] Incorrect output in example

### ISSUE THREAD

**Issue by mandolinraman** [jmschrei/pomegranate#961]
Hello!

I'm super excited to have found this library. I haven't check the source code but as I play with it I think that the the CG-island output in your example is incorrect. Wouldn't it make sense to extend the CG state `0` one more time-step given that the next emission is a `G`? The overall cost of transitions is the same but the emission is more likely:
```
sequence: CGACTACTGACTACTCGCCGACGCGACTGCCGTCTATACTGCGCATACGGC
hmm pred: 111111111111111000000000000000011111111111111110000
   extend the 0 state at this position---^
```
There were other random examples like this one. Having two transitions (`CG island` -> `background` -> `CG island`) would scale the path probability by (0.1/0.9)^2 = 1/81 but the benefit due to the emissions `AT` from the background state can only boost it by (0.25/0.1)^2 = 6.25.
 
```
seq = numpy.array(list('CCGCACGCCCGCTATCTACATTACTGTAAGCCAGCGATCGGCC'))
hmm_predictions = model.predict(seq)
print("sequence: {}".format(''.join(seq)))
print("hmm pred: {}".format(''.join(map( str, hmm_predictions))))
sequence: CCGCACGCCCGCTATCTACATTACTGTAAGCCAGCGATCGGCC
hmm pred: 0000000000001111111111111111111110001100000
  costly to switch states for two time-steps--^^
```

**Comment by jmschrei** [comment]
Hi Raman

Thanks for looking into this.

I don't think either is a bug. Rather, it's an artifact of the default
algorithm for the "predict" function using maximum a posteriori (MAP)
decoding which is the sum over all paths, in contrast to the Viterbi
decoding which is the maximally likely single path. Sometimes the MAP path
is less intuitive than the Viterbi path because each step involves the sum
over all possible alignments of states to observations and so can sometimes
produce a different alignment than the maximally likely path, but is more
robust to noise. You can use the `viterbi` function or pass `"viterbi"`
into the `predict` function to get Viterbi decoding. I think the problem is
basically that, summed over all possible paths, the state probabilities at
those positions are very close to 50-50. You could check this yourself by
using the `predict_proba` function and seeing whether the predicted state
probabilities are close to 50-50 in those positions. If so, this is also a
weakness in using discrete predictions versus always staying in probability
space.

In general, it's not good practice to suggest that there might be a bug in
a repository based on the feeling that results are not correct without even
checking the source code or documentation or looking into it further. It's
much better practice, and more useful to everyone, if you take this
suspicion and tinker around with it to confirm that something is, indeed,
working incorrectly and in what cases it's clearly doing the wrong thing.
Something might be wrong but, unfortunately, I don't have time to
investigate the code without a more obvious failure case.

Let me know if you look into this more.
Jacob

**Comment by mandolinraman** [comment]
Hi Jacob,

I agree with your comment about MAP vs. Viterbi and for apologize for not checking that Viterbi wasn't the default option. I just tried the Viterbi option and saw an unexpected output (both length and values).

```
In [45]: seq = numpy.array(list('CGACTACTGACTACTCGCCGACGCGACTGCCGTCTATACTGCGCATA
    ...: CGGC'))
    ...:
    ...: hmm_predictions = model.predict(seq, 'viterbi')
    ...:
    ...: print("sequence: {}".format(''.join(seq)))
    ...: print("hmm pred: {}".format(''.join(map( str, hmm_predictions))))
sequence: CGACTACTGACTACTCGCCGACGCGACTGCCGTCTATACTGCGCATACGGC
hmm pred: 2111111111111111111111111111111111111111111111111111
```

However, I'll close this issue though since I do want to check the source and documentation first.

Thanks again!
Raman

**Comment by jmschrei** [comment]
The Viterbi algorithm produces a sequence of states that includes silent
states, such as the start state (you'll note index 2 in a 2-state model).
It is possible that the model chosen, and the sequence I designed, isn't
sensitive enough using Viterbi. I wrote the example quickly without
thinking too much about it.

**Comment by mandolinraman** [comment]
Thanks! I'll play with it some more.
