### ISSUE TITLE
Support for Apple Silicon?

### ISSUE THREAD

**Issue by MariaLavrovskaya** [jmschrei/pomegranate#963]
**Describe the bug**
No suitable architecture for Apple Silicon. Is there any plans to do Apple Silicon support?

**Comment by ttamg** [comment]
For anyone taking a look for this, pomegranate at this time does not work on Apple Silicon if installing via `conda install -c anaconda pomegranate` because there is no suitable architecture available.

However it does currently work if installing on Apple Silicon via pip with `pip install pomegranate`

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
