### ISSUE TITLE
Forward probabilities don't add up to 1 ?

### ISSUE THREAD

**Issue by teoML** [jmschrei/pomegranate#984]
Hi! I implemented an HMM and then I wanted to check the forward probabilities of a sequence. As far as I understand, the forward() function returns a matrix where each row represents the log probability of each state for the given observations at time t. My code looks like this: 
```
import pomegranate
from pomegranate import *
hmm_model = HiddenMarkovModel(name = "Jurafsky example")

c_emissions = DiscreteDistribution({"0":0.5, "1":0.4, "2":0.1})
c_state = State(c_emissions, name="Cold")

h_emissions = DiscreteDistribution({"0":0.2, "1":0.4, "2":0.4})
h_state = State(h_emissions, name="hot")


hmm_model.add_states(c_state, h_state)
# add the transitions

hmm_model.add_transition(hmm_model.start, c_state, 0.2)
hmm_model.add_transition(hmm_model.start, h_state, 0.8)

hmm_model.add_transition(c_state, c_state, 0.5)
hmm_model.add_transition(c_state, h_state, 0.5)
hmm_model.add_transition(h_state, h_state, 0.6)
hmm_model.add_transition(h_state, c_state, 0.4)

hmm_model.bake()

forward_matrix = hmm_model.forward(["2","0","2","2"])
```
The output  for forward_matrix contains the log probabilities, but after applying the exp() function I found out that don't add up to 1 (except the first row which corresponds to the start state).
You can see the code here: https://colab.research.google.com/drive/11nouOptxrncafPaGvbdHmd2pp4sDKA8c?usp=sharing

Why is that so?

**Comment by jmschrei** [comment]
The forward algorithm alone is just iteratively taking the previous row, adding the log probabilities of transitions, and adding the vector of observation log probabilities under each state. Each entry answers the question "what is the probability that I started at the beginning of the sequence and took ANY path to align this observation to this state?" The "ANY" is key, because the Viterbi algorithm is answering "what is the BEST path." When selecting out the end state from the final row this gives the log probability of the entire sequence under the model, i.e., the sum-of-all-paths probability. 

What you're looking for is the emission matrix from the forward-backward algorithm which is answering "given that I started at the beginning of the sequence aligning observation to states, and after this observation go on to align characters to the model until the end, what is the probability of each model component given this observation?" Both clauses at the beginning are important because it's not the independent alignment of that observation to the states alone -- you have to align the observation to a state in a manner that is consistent with the prior observations AND the subsequent ones. Hence, needing to run both the forward and backward algorithms and merging the results.  

You can do this using `model.forward_backward`, which will return both the expected transition matrix and the expected emissions matrix, or `model.predict_proba` which is just the expected emissions matrix.

**Comment by teoML** [comment]
@jmschrei  thanks for your answer! I think I understand it. But one last question regarding this - i can still turn this values into real probabilities which sum up to one by dividing each probability by the sum, right ? In that way I will get a proper probability distribution. 
By the way, I don't think that the forward-backward is really applicable in my case - I am trying to do activity recognition (in real time) and hence I can only see the observations until a given time t. So the system basically will find the most probable state for each new observation.  I think that if I use  model.predict_proba() on an input sequence it will deliver a misleading result, since  the forward-backward algorithm considers previous and future states. For other tasks, such as NER, predict_proba() is of course perfect, since we can observe the whole sentence and then do the inference, but in my case I want to get the probability of each state for timestep t given all observations including the ones at time t.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
